### ISSUE TITLE
DNS Issue - Cloudflare - CNAME cross user banned

### ISSUE THREAD

**Issue by digitaldesigndj** [HermanMartinus/bearblog#1]
I am trying to point my custom subdomain bear.hyprtxt.dev for my blog at hyprtxt.bearblog.dev. My Hyprtxt.dev DNS is at Cloudflare. I am getting an error 1014 from Cloudflare.

https://hyprtxt.bearblog.dev/
https://bear.hyprtxt.dev/

Perhaps something to do with SSL? I am not quite sure. Love it so far!

**Comment by HermanMartinus** [comment]
Hey Taylor, I was just about to email you. I just realised that setting the
CNAME record to subdomains.bearblog.dev will only work in some instances
(because of cloudflare). You can set your CNAME record to
intense-shallot-9foagelzs54op9wrom8ybsbn.herokudns.com instead and it
should work. I've updated the doc.

Thanks for bringing this to my attention :)
Herman

**Comment by digitaldesigndj** [comment]
Awesome! Happy to help. Looks like I borked both blogs with Cloudflare. 😄 

https://hyprtxt.bearblog.dev/

I like what you got.

**Comment by HermanMartinus** [comment]
That was actually me. Tried fixing a problem, broke something else ;) It's
working now https://hyprtxt.bearblog.dev/


You can set your CNAME to this one, and it should work :P
shaped-krill-fusn49u0rpoovwvgh0i6za5w.herokudns.com

Sorry about that!
Going back to manually updating a bunch of borked records ;)

**Comment by HermanMartinus** [comment]
Huh, I realise I need to do some stuff to get SSL working for .dev domains since it's not going through cloudflare anymore 😑

**Comment by HermanMartinus** [comment]
Cool, so https://bear.hyprtxt.dev won't work unless it has an ssl cert, so it will work if it gets proxied on a CDN like cloudflare. I'm still trying to figure out how to give eveyone SSL certificates while staying free :)

**Comment by digitaldesigndj** [comment]
It works great from the heroku cname. My domain is dev too and I use
certbot nginx, not just cloudflare. 👍

**Comment by digitaldesigndj** [comment]
Ohh it worked for a second there. Certbot on you side is a much taller
order. Star sub domain very may do it though.

**Comment by HermanMartinus** [comment]
Yeah, sorry, what caused the commotion is I actually deleted that record. So `shaped-krill-fusn49u0rpoovwvgh0i6za5w.herokudns.com` is now the official one. It's been a wild last 5 hours. Hacker News Hug is real. 😅

**Comment by iaserrat** [comment]
Hi, I'm still getting: 

```
This site can’t provide a secure connection1taco.dev sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

for `1taco.dev`

**Comment by HermanMartinus** [comment]
@iaserrat Are you proxying through a service like cloudflare? Bear doesn't currently issue certificates. Also in the setup, SSL connection type to Flexible.

**Comment by iaserrat** [comment]
My bad, I set the connection mode to Full. Thank you!

**Comment by HermanMartinus** [comment]
I'm working on getting better certificate management :)

**Comment by HermanMartinus** [comment]
Updated docs to include Flexible instructions

**Comment by keshavrai** [comment]
Hey Herman, 

Just upgraded for the custom domain feature. 
keshavrai.bearblog.dev to keshavrai.in
My DNS is at Namecheap. Please help when I configured the CNAME to keshavrai.in and Value domain-proxy.bearblog.dev.
It's showing me an error. 


@HermanMartinus

**Comment by avinashkanaujiya** [comment]
I think you can

> Hey Herman,
> 
> Just upgraded for the custom domain feature. keshavrai.bearblog.dev to keshavrai.in My DNS is at Namecheap. Please help when I configured the CNAME to keshavrai.in and Value domain-proxy.bearblog.dev. It's showing me an error.
> 
> @HermanMartinus

I think you can't use CNAME on root domain directly, you should set it for www subdomain and then set forwarding for root domain to www.yourdomain.net

**Comment by keshavrai** [comment]
> > Hey Herman,
> > Just upgraded for the custom domain feature. keshavrai.bearblog.dev to keshavrai.in My DNS is at Namecheap. Please help when I configured the CNAME to keshavrai.in and Value domain-proxy.bearblog.dev. It's showing me an error.
> > @HermanMartinus
> 
> I think you can't use CNAME on root domain directly, you should set it for www subdomain and then set forwarding for root domain to [www.yourdomain.net](http://www.yourdomain.net)

Can you help me out with instructions? 
Should I add name as www with value to domain-proxy.bearblog.dev and then add another CNAME of keshavrai.in and value to domain-proxy.bearblog.dev ?

@avinashkanaujiya 


@HermanMartinus Some support for paid users would take you a long way.

**Comment by keshavrai** [comment]
Seems to be working now thanks @avinashkanaujiya 

Does the Made with bear footer stick even after upgrading account? There seems to be no toggle to turn it off.

**Comment by avinashkanaujiya** [comment]
Just add a CSS in either Nav or in Styling, which sets the display of
footer tag to none.

On August 17, 2022, Avinash A K ***@***.***> wrote:
> Seems to be working now thanks @avinashkanaujiya
> <https://github.com/avinashkanaujiya>
>
> Does the Made with bear footer stick even after upgrading account?
> There seems to be no toggle to turn it off.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/HermanMartinus/bearblog/issues/1#issuecomment-
1217182681>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AF6QX7NQAMFB26UB6EQNUCDVZQBPJANCNFSM4NKZGELA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by HermanMartinus** [comment]
@keshavrai It looks like your issue was that the DNS records were just taking time to propagate (this can take seconds to hours depending on your domain registrar) and not an issue with Bear itself.
