### ISSUE TITLE
Matching subdomain error being thrown badly

### ISSUE THREAD

**Issue by HermanMartinus** [HermanMartinus/bearblog#10]
`DETAIL: Key (subdomain)=(testblog) already exists.` 

or 

```
IntegrityError at /dashboard/
duplicate key value violates unique constraint "blogs_blog_slug_key"
DETAIL:  Key (subdomain)=(k) already exists.
```

**Comment by HermanMartinus** [comment]
This error is being thrown without the user knowing and I just get an email error

**Comment by DivisionMax** [comment]
What is the flow to replicate this issue?

I created a user and used the "testblog" subdomain.
I created another user and used the same "testblog" subdomain, but it correctly returned "Blog with this Subdomain already exists." in the form.
