### ISSUE TITLE
Some text with angle brackets in a single line code block cannot be shown

### ISSUE THREAD

**Issue by undr22** [HermanMartinus/bearblog#100]
<img width="491" alt="截屏2021-07-22 下午4 56 35" src="https://user-images.githubusercontent.com/55726154/126613760-10e13ba3-fb30-4b48-b186-190d7f6db339.png">

<img width="477" alt="截屏2021-07-22 下午4 56 48" src="https://user-images.githubusercontent.com/55726154/126613770-0d40f599-624d-44a3-8308-038e5ed546fa.png">

**Comment by HermanMartinus** [comment]
`<some text>`

Hmmm, Bear is currently using Mistune as the markdown renderer. I'll take a look into is and see what's happening.

**Comment by HermanMartinus** [comment]
Fixed in lastest Mistune update
