### ISSUE TITLE
Issue HTTPS certificates with Sewer https://github.com/komuw/sewer

### ISSUE THREAD

**Issue by rphlo** [HermanMartinus/bearblog#103]
Sewer https://github.com/komuw/sewer is a ACME v2 python client.

I have implemented similar feature for a similar django site that is hosted on a VPS behind nginx.

I read this bearblog code to inspire me for CNAME feature and later added management commands to issue certificates.
Bearblog being hosted on heroku there might be some adjustment to do, but I feel my code could be a good start to automate HTTPS on custom domain.

See my code:
https://github.com/routechoices/routechoices-server/blob/master/routechoices/core/management/commands/create_certificate.py
https://github.com/routechoices/routechoices-server/blob/master/routechoices/core/management/commands/renew_certificate.py

**Comment by HermanMartinus** [comment]
Thanks, I'll take a look through it. I currently have a semi-automated process to issue certs. The issues I'm running into is that there's a lot of bad entries that I need to filter.

**Comment by HermanMartinus** [comment]
Currently automatically issuing certificates with Caddy

**Comment by mholt** [comment]
@HermanMartinus Caddy / CertMagic is the right tool for the job. Let me know if you have any questions about it. :slightly_smiling_face:

**Comment by HermanMartinus** [comment]
Hey Matt, Caddy is working like magic. Thanks for the assistance with the Digital Ocean [issue](https://caddy.community/t/solved-caddy-not-proxying-requests-with-tls-on-demand/16075/8) I had in setting it up. 🚀
