### ISSUE TITLE
Can't add CNAME to DNS on Cloudflare

### ISSUE THREAD

**Issue by conifer-dev** [HermanMartinus/bearblog#105]
Unable to add the required CNAME over at Cloudflare to port over my domain.
I'm getting an error of:

An A, AAAA, or CNAME record with that host already exists. (Code: 81053)
There is no content of any CNAME on my DNS. I could only add TXT required one.

**Comment by minthemiddle** [comment]
You probably have your old A or CNAME record taken over. Remove the old one first and add Bear in the second step.

**Comment by HermanMartinus** [comment]
Closing stale issue
