### ISSUE TITLE
Filter by language

### ISSUE THREAD

**Issue by Zughy** [HermanMartinus/bearblog#110]
It'd be nice to have a setting to optionally declare in which language a post has been written, and to use this setting to filter posts in the discovery feed. A lot of entries are in English, so if I want to search for, I don't know, Spanish entries, I have to navigate through a lot of things I'm not interested in.

There could be an option in the blogger profile containing the default language (English by default), so that it applies on every new post IF not manually changed in the post settings

**Comment by HermanMartinus** [comment]
I'll give some thought to filtering in the discovery feed by language. As for individual blogs, a person can do the following:
Add an "English" tag to all of your English posts and a "Spanish" tag to all of your Spanish posts. Then in your nav you can include the query param `[Spanish posts](https://yourblog.bearblog.dev/blog/?q=Spainish)`

**Comment by HermanMartinus** [comment]
The above still applies for filtering posts, but now you can add post-specific language by specifying the `lang` in the post header.
