### ISSUE TITLE
Custom domain not working, maybe due to CNAME

### ISSUE THREAD

**Issue by minthemiddle** [HermanMartinus/bearblog#113]
I set up DNS to Cloudflare and followed the advice on the wiki.

Nameserver and TXT are set up correctly.

```
dig martinbetz.net -t NS
dig martinbetz.net -t TXT
```

When you try to connect to `martinbetz.net` though, you get a Heroku error "There's nothing here, yet.".

One potential problem is the CNAME on root domain level. This is not an RFC compliant setting and though Cloudflare seems to support it with a workaround, it complains:

![image](https://user-images.githubusercontent.com/1950766/148177221-7ce635d9-b256-4a69-8af5-a24579790782.png)

The tooltip says:

"Because CNAME records are not allowed at the zone apex (RFC 1034), CNAME flattening will be applied to this record."

What am I doing wrong?

**Comment by bedirekim** [comment]
Same here. Also, there is an error message: Record conflicts with an existing CNAME record on the same host.

**Comment by HermanMartinus** [comment]
Thanks for reporting this. It looks like the Heroku API has changed slightly around domain management. I'll take a look at this when I get a chance and will pop an update here when it's working again.

**Comment by HermanMartinus** [comment]
Updated the api call as per Heroku's new required parameters

**Comment by bedirekim** [comment]
I am still getting errors. @HermanMartinus

**Comment by KangOl** [comment]
Actually, it's a design issue: `CNAME` cannot be set along with other records
The [RFC1034](https://www.rfc-editor.org/rfc/rfc1034#section-3.6.2) states
> If a CNAME RR is present at a node, no other data should be
present; this ensures that the data for a canonical name and its aliases
cannot be different.

Also, `pdnsutil check-zone $ZONE` gives the following error
```
[Error] CNAME $ZONE found, but other records with same label exist.
```
