### ISSUE TITLE
CSS rule typo: word-wrap

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [HermanMartinus/bearblog#115]
The body element has the rules

```
word-wrap: break-word;
overflow-wrap: break-word;
```

https://github.com/HermanMartinus/bearblog/blob/2ee04f04efa172fd32b63d0480692f405106b943/templates/styles/main.css#L8-L9

However, there is no such rule as word-wrap. The correct rule name is [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

I did not submit a PR because I am not sure what the intended goal is. MDN says the break-word value for word-break is deprecated and

> Has the same effect as word-break: normal and overflow-wrap: anywhere, regardless of the actual value of the overflow-wrap property.

**Comment by HermanMartinus** [comment]
`break-word` is correct. If you follow the [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) link you'll see it specifies `break-word` in it.

**Comment by ilmari-lauhakangas** [comment]
> `break-word` is correct. If you follow the [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) link you'll see it specifies `break-word` in it. I believe `word-break: break-word` is deprecated, but we're using `word-wrap: break-word`. https://www.w3schools.com/cssref/css3_pr_word-wrap.php

break-word is correct, but the rule name is not. You're using word-wrap, which is an imaginary rule name.
