### ISSUE TITLE
Please add IPv6 support to https://bearblog.dev/

### ISSUE THREAD

**Issue by amreo** [HermanMartinus/bearblog#118]
Hi!
I want to simply ask: add support to ipv6 for https://bearblog.dev/
The reason is simple: because it's future proof.

**Comment by HermanMartinus** [comment]
This is unfortunately not possible until Heroku supports IPv6 

https://devcenter.heroku.com/articles/http-routing#not-supported

**Comment by HermanMartinus** [comment]
So, I've added IPv6 support by routing through a reverse proxy using Caddy and digital ocean. To activate IPv6 support do the following: 

**Delete the following DNS record:**
CNAME | {your domain or subdomain} |     shaped-krill-fusn49u0rpoovwvgh0i6za5w.herokudns.com

**Add the following DNS records:**
A             | {your domain or subdomain} |      159.223.204.176
AAAA     | {your domain or subdomain} |      2604:a880:4:1d0::30e:7000

**Comment by amreo** [comment]
Thank you
