### ISSUE TITLE
[Request] Tutorilas Needed

### ISSUE THREAD

**Issue by bkrucarci** [HermanMartinus/bearblog#119]
As the title told. Are there any tutorials for novice users?

I saw some bearblogs and thye looks very nice and different. I cannot add "Nav" options.. Like Blog, Projects, About sections for example.
Just need tutorials to use effectively.

Thanks

**Comment by Cwpute** [comment]
What would you like to know exactly ? i've found most of Bearblog pretty self-explanatory.

If you're referring to CSS custom styles, then i can understand, as i've been trying to understand how they work myself. And with not any background in CSS prior to blogging on Bearblog, it's been a bit rough trying to make my blog look cool and all. I've succeeded in copy-pasting already existing css styles, and have just now began to dwelve into making my own custom css style, so if you want help on that i can give you some vague advice 😅

**Comment by HermanMartinus** [comment]
All the content in Bear uses Markdown syntax (there's a cheat sheet below each field to help you if you get stuck). I've also set up a quick tutorial for you here: https://github.com/HermanMartinus/bearblog/wiki/Navigation
