### ISSUE TITLE
Please Consider Registering Brave Creators Program to Collect Contribution

### ISSUE THREAD

**Issue by bkrucarci** [HermanMartinus/bearblog#121]
Hi @HermanMartinus ,

Please register your websites to Brave Creators Program to collect some contribution form users.
https://creators.brave.com/

I can tip my tokens to you. People can tip their tokens which collected by surfing the web. (PayPal currently not usable in my region. This solution will help on this matter.) This model seems very useful to me and to you too.
What do you think?

**Comment by HermanMartinus** [comment]
Hi @bkrucarci, thanks for the suggestion. 

Unfortunately this falls outside the scope of this project. I'm also very hesitant to even tangentially include blockchain products in Bear. 

That being said, I am looking at alternative ways of payment (as PayPal is not without it's issues, but is unfortunately one of the only methods available in my region).

**Comment by bkrucarci** [comment]
@HermanMartinus you can add your Github profile for Brave Creators Program! After that, put an alternative method to your "Contribute" page on your bear blog page. Then a link which forwards the people to your account and tip! Think of it like going around

**Comment by HermanMartinus** [comment]
I appreciate the idea :) At the moment I'm mostly supporting Bear as a passion project. In the future if I decide to move over to this full time I'll consider better methods of accepting contributions

**Comment by bkrucarci** [comment]
Ok then :) I love BearBlog & trying to help it to make it immortal! I use it for my all guides and essays. I do not want them perish.
Thank you have a nice day. I'll close the issue.
