### ISSUE TITLE
Footnotes not working

### ISSUE THREAD

**Issue by son-of-lilith** [HermanMartinus/bearblog#122]
I followed the instructions at https://herman.bearblog.dev/markdown-cheatsheet/ yet footnotes do not work properly.

**Comment by HermanMartinus** [comment]
I can't help you without more information. Footnotes do work (in the link you sent me that is apparent). I can't tell why they aren't working for you without an example of what you're trying to do.

**Comment by HermanMartinus** [comment]
https://herman.bearblog.dev/footnote-test/?preview=true

It looks like you need to put an extra space under `footnotes:` so that the markdown parser pushes it to the next line.

```
Test[^1]

footnotes:

[^1]: this is a footnote.
```
