### ISSUE TITLE
Allow self-hosted Fathom usage

### ISSUE THREAD

**Issue by Steellow** [HermanMartinus/bearblog#126]
Fathom can be self-hosted for free on [Heroku](https://github.com/usefathom/fathom/blob/master/docs/misc/Heroku.md) for example. Since Bear already has support for Fathom analytics, it would be great to be able to use self-hosted Fathom as well.
If you set the Fathom ID from analytics tab it always uses the script source, so self-hosted instances don't work atm

https://github.com/HermanMartinus/bearblog/blob/eab4b5dbb73822ac79555c49b07307e49055b840/templates/home.html#L15-L19

**Comment by jakobbouchard** [comment]
Similar to this, support for [umami](https://github.com/mikecao/umami) instances could also be nice! And for Fathom, support for CNAME/custom domains, since they do offer this too!

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io/). Github issues reserved for bugs going forward.
