### ISSUE TITLE
Add ability to customize 'Blog' page

### ISSUE THREAD

**Issue by Disil** [HermanMartinus/bearblog#129]
The page that shows latest post (_insertblogname_**.bearblog.dev/blog**) is static. It cannot be customized to add simple paragraph. 

This would be useful for any writer, where they can add disclaimer above the post list.  For example, if this feature is implemented, then I can add a _mini tutorial_ on how to following the blog by using RSS, because rss are rarely used/unknown to public in current years. 

Here's the illustration of the concept:
![bearblog feature request-customizable static page](https://user-images.githubusercontent.com/26422376/165707220-16235b7b-437a-4bad-a115-62460b140670.png)

**Comment by fengzihub** [comment]
You can add a navigation page to the navigation bar.

<img width="538" alt="截屏2022-05-08 20 13 57" src="https://user-images.githubusercontent.com/16876023/167295639-73446c20-bd13-4341-8fdd-3b321d12ac61.png">

<img width="383" alt="截屏2022-05-08 20 10 35" src="https://user-images.githubusercontent.com/16876023/167295653-43e5b482-cc42-4f41-b965-9ee89de1206f.png">

<img width="343" alt="截屏2022-05-08 20 10 49" src="https://user-images.githubusercontent.com/16876023/167295659-b08be7e2-6583-41b1-8264-4574f3a16407.png">

Hope it can help you !

**Comment by Disil** [comment]
> You can add a navigation page

No, that's not what i meant. What I want is the ability to customize the 'space' between navigation bar and content text in Blog page (the page that displaying latest post)

**Comment by mbluelander** [comment]
I'd like this too, but in the meantime you can add a little bit of custom text with a pseudo-selector for the blog list. I used it to add a simple header to the top, to make it match the other pages:
```
ul.blog-posts {margin-top:2rem;}
ul.blog-posts:before {content:"blog"; font-size:2em; font-weight:bold;}
```

cf. https://bluelander.bearblog.dev and https://bluelander.bearblog.dev/tags

**Comment by fengzihub** [comment]
@Disil 
Oh, sorry, I misunderstood.

**Comment by HermanMartinus** [comment]
What I would suggest if you'd like a custom blog page is to create a new page and add the links, dates, titles, and descriptions as you see fit. Unfortunately I can't change the format of the `/blog/` page to suit everyone ;)
Example:

```
*22 June, 2022* - **Super awesome title!**
Some neat description of how good the content of this article is.

*22 June, 2022* - **Super awesome title!**
Some neat description of how good the content of this article is.

...
```
Which will look something like

*22 June, 2022* - **Super awesome title!**
Some neat description of how good the content of this article is.

*22 June, 2022* - **Super awesome title!**
Some neat description of how good the content of this article is.
