### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by voanhcuoc** [HermanMartinus/bearblog#13]
Thank you for your great effort.

Is code highlighting conflict with this project's philosophy? I'm confused because it requires heavy stylesheet. But it's very useful to have.

**Comment by HermanMartinus** [comment]
I'm on the fence about that. I think I'll make it optional to the user in a later build.

**Comment by nickes** [comment]
I'm trying to add code snippets to my post, but somehow the block with the ``` didn't work. I thought that i would get the same result as in your Markdown test page. Can you tell me the correct syntax?

**Comment by HermanMartinus** [comment]
if (data_bar(2) > 5) {
        process_tcp_expression.xp += 8;
        analystAppleTechnology = title;
        irqDdrOverclocking = 413288 + ssd_cyberbullying;
    }
    var fifo_adapter_flash = disk_active + 88;
    if (io.nicCiscGateway(lifo_http, disk, 2) + bareHdv) {
        box_dtd = kdeCmsComputing(1, isoCompiler, compression);
        thermistor_interpreter_netiquette.up_directory_iphone(
                up_wysiwyg_webmail(kbps));
        languagePc = view_rw_drag.device(directVirus, web_formula);
    } else {
        responsive += 39 + link_perl;
    }

**Comment by HermanMartinus** [comment]
It's just 4 spaces before each line
    print(hi)

**Comment by HermanMartinus** [comment]
This is test

    code()

**Comment by HermanMartinus** [comment]
Okay, it's 4 spaces before each line with a bank line on each side of the code block.

**Comment by nickes** [comment]
Great, Thanks
