### ISSUE TITLE
Lighthouse docking points for maximum-scale in meta viewport tag

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [HermanMartinus/bearblog#130]
**Summary**
Currently seeing an issue in Lighthouse around zoom with iPhones.
![image](https://user-images.githubusercontent.com/2762119/166405923-c9f5e301-c28d-4c18-833d-695205f527a9.png)

It's due to the maximum-scale attribute there, which MDN has a suggestion to not use, and there's an alternative solution to better display these pages on a landscape mobile screen
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_width_and_screen_width

**Comment by HermanMartinus** [comment]
Resolved in b78ea5e8e045e4243daa62242dd5e655b3c4f3d0
