### ISSUE TITLE
Simple hyperlinks in angle brackets with an @ character get turned into mailto: links

### ISSUE THREAD

**Issue by mbluelander** [HermanMartinus/bearblog#132]
Mastodon profile URLs contain an @, so for example

`<https://mastodon.social/@mastodon>`

Becomes a link to <mailto:https://mastodon.social/@mastodon>

**Comment by HermanMartinus** [comment]
Huh, looks like that's a feature of the markdown renderer. TBH I don't want to go and do any more overwriting of it cause it gets messy. In this case you can set up the link like so:

```[https://mastodon.social/@mastodon](https://mastodon.social/@mastodon)```

Which should render like so: 

[https://mastodon.social/@mastodon](https://mastodon.social/@mastodon)

**Comment by HermanMartinus** [comment]
Just as a test I want to see how Github handles this:

<https://mastodon.social/@mastodon>

**Comment by HermanMartinus** [comment]
I've opened an [issue](https://github.com/lepture/mistune/issues/302) on the markdown renderer

**Comment by mbluelander** [comment]
Thanks! It's such a minor issue I feel silly even calling it an "issue", just thought it was something you might not notice but would like to address eventually. Thanks for all your hard work.

**Comment by HermanMartinus** [comment]
Turns out I just needed to update the markdown renderer. Fixed in cc4ef4d6e9b68be9be461fd3a530f33c959c99f6

Test:
https://herman.bearblog.dev/embed/?preview=true
