### ISSUE TITLE
Post by email

### ISSUE THREAD

**Issue by hschauhan** [HermanMartinus/bearblog#134]
Can there be a way where we sent the markdown as plain text email and it is posted as blog?

**Comment by alexlehm** [comment]
I was thinking that as well when I started trying out the blog just now, sortof a Posterous-like feature.

This would be easy to implement if a POST API is available when you can run your own email server, but it might make a useful feature on the site (probably as a premium feature)

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io/). Github issues reserved for bugs going forward.
