### ISSUE TITLE
How to customise page footer

### ISSUE THREAD

**Issue by ohong** [HermanMartinus/bearblog#135]
Hi there, I'm new to Bear Blog - rly cool project! Unless I'm missing something obvious, is there any way to update the footer for the entire site, or for a specific page (i.e. where the default is "Made with [Bear ʕ•ᴥ•ʔ](https://bearblog.dev/)")?

Is that a premium / paid feature?

Thanks in advance for your answer!

**Comment by HermanMartinus** [comment]
Thanks for the kind words. There is currently no way to change the universal footer at the moment. It's a feature I'll consider for future addition :)

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io/). Github issues reserved for bugs going forward.
