### ISSUE TITLE
Change the default homepage

### ISSUE THREAD

**Issue by nicolastjt** [HermanMartinus/bearblog#136]
Will there be a way to change the default homepage to another page? For instance, have the "blog" page as the root, and the previous "home" become a secondary "about" page?

**Comment by HermanMartinus** [comment]
If you leave the homepage blank it becomes the blog page. You can then create an about page and use that for the about page.

**Comment by Brin-o** [comment]
Could I just suggest adding this to the docs? Maybe in the navigation section? Thats where I checked first.
