### ISSUE TITLE
Import from text file(s)

### ISSUE THREAD

**Issue by nicolastjt** [HermanMartinus/bearblog#137]
I know the import/export feature is on the roadmap, but I was curious as to what it could mean, especially regarding having a bunch of text files, with metadata in them (for tags, dates, permalink). Also, any plan of making it possible to upload a text file (.txt or .md, via browser or email) to publish a new blog post, instead of copy/pasting in the window?

Thanks!

**Comment by HermanMartinus** [comment]
Unfortunately creating a blog post by uploading a file is not in the works. The import/export is for the blog as a whole. It may be a bit inconvenient to copy/paste the text into the post, but I think it's not so bad as multiple content creation methods.
