### ISSUE TITLE
navigation to Posts from home page

### ISSUE THREAD

**Issue by morganeparker** [HermanMartinus/bearblog#139]
Hi!

When I click on Posts from the homepage it says page not found. 

In my dashboard > navigation
It looks like the attached screenshot. [](url)

Then when I view the blog and click on Posts it says page not found. I am new at this and I cannot figure what I need to do to fix the Posts page to display all of my posts.

Any help would be much appreciated. 

Thank you,
Morgan
<img width="217" alt="Screen Shot 2022-05-15 at 13 10 17" src="https://user-images.githubusercontent.com/37886385/168485275-c9eaca2d-febe-463c-add9-feb0b997897a.png">

**Comment by mbluelander** [comment]
By default, all the blog posts are listed on /blog/. If you change the (/Posts/) to (/blog/) the link should work.

You can create a page called /Posts/, but it would just be a blank page you can edit. The auto-generated list of posts can only be at /blog/ (or on the homepage, if you don't have anything else there.)

**Comment by HermanMartinus** [comment]
@mbluelander that is correct, thanks :)
