### ISSUE TITLE
Add support for creating bilingual/multilingual websites

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [HermanMartinus/bearblog#141]
Ideas (don't know if they are even possible or not):
- let users choose a default language (practically)
- do not let users create duplicate languages (practically)
- add a directory for the new language; for example, like /fr/ and having the same structure as root in that /fr/ directory. If the user has 2 languages (e.g. English + French), home page (/) shows the default language and second language takes place at /fr/.
- make language-specific dashboards 
- Add navbar element (link) to the other language(s) by default

P.S. I have read #110, but the provided solution seems incomplete. For some reasons:
- Different languages have different needs. I mean, there are a lot of things to tweak that are specific per language. Take navigation bar elements as an example. Or custom CSS styles (Specially for RTL languages)
- It would just be so much cleaner and neater

**Comment by HermanMartinus** [comment]
Localisation of this level is unfortunately not going to be possible here as it would need a massive architectural overhaul to essentially support 2 blogs in one. What I would recommend doing here is starting a second blog and sub-domaining it at eg: `fr.yourblog.com` or `en.yourblog.com`

**Comment by HermanMartinus** [comment]
You can now add post-specific language by specifying the lang in the post header. This solves the language specification. There are multiple ways to handle showing the delineation from different language posts using filters or by creating custom pages. For more control I still suggest running 2 blogs, one for each language.

**Comment by victor-marino** [comment]
Hi @HermanMartinus.

Piggybacking on this to avoid opening a new discussion, as I'm one of those weirdos that would like to have a "language switch" in my site :)

Regarding your proposed solution of running two separate blogs with language subdomains, some questions from my side:
* Would there be any possibility of sharing the same subscription fee to pay for both? (as custom subdomains would always require upgrading to premium).
* In the nav links, would it be possible to create a sort of "dynamic" link that will always redirect to the `http://en.***` subdomain version of the current page? That way all one would need to do is to mirror the same URL structure across pages and posts in both blogs, and the nav button would effectively work as a language switch.

**Comment by victor-marino** [comment]
And now thinking of possible workarounds to make this work *without* subdomains (as I think is a bit cumbersome):

In my case, I'm mostly interested in translating the "static" pages of my website: "About me", "Projects" and "Contact"; as these act as a kind of presentation card that I want to localize. The blog itself isn't that critical to me: I will typically write posts either in English or in Spanish, but not both, so I don't mind visitors seeing the full post list and choosing what to read.

For the static pages, an easy solution is to create two versions of each page. For example:
* `mywebsite.com/sobre-mi` (in Spanish)
* `mywebsite.com/about-me` (in English)

And then add something like this at the top-right of each page so it acts as a "language switch".

In the Spanish page:
```html
<div style="text-align: right"><a href="https://mywebsite.bearblog.dev/about-me">Switch to English</a></div>
```
And in the English page:
```html
```html
<div style="text-align: right"><a href="https://mywebsite.bearblog.dev/sobre-mi">Cambiar a español</a></div>
```

This works well enough for that specific page. However, the navbar would still point to one version of each page only, which would be confusing for a user who has already switched to the other language.

* Any chance we could tweak the navbar somehow so that links point to a different link depending on the page we're currently in?

If subfolder pages were supported (e.g.: `/en/about` and `/es/about`), I guess we could just have an option to have the navbar prepend the current page language code to the relative link. E.g.: if the current page language is set to `es-ES`, add `es` to the relative link: `http://mysite.com/es/about`.

But I tried and it's not possible to publish pages to a "subfolder" right now. If I enter `es/about` as the page link, it gets stripped to `esabout`.

Any thoughts on this?

I feel like we're actually close to supporting about 90% of the stuff that matters, but it would still require a couple of new features of course.

**Comment by HermanMartinus** [comment]
Very interesting comments :) 

First off, if you upgrade you can open up to 10 blogs with full featuresets. So no worries about upgrading multiple blogs. 

There is definitely some clever JS you can write to get dynamic links to display, but I think the most concise way would be to have two post lists on the same blog using tags, and then manually adding the "Read in english/spanish" link to the other version of the post. 

Currently Bear doesn't handle paths `/en/about/` but I'm seriously considering it. In the meantime, though, it should be trivial to manage it well. I have https://justsketch.me running on Bear which handles 4 different languages.

**Comment by victor-marino** [comment]
Ah, hadn't realized about the 10-blog thing. That part is covered then!

So if we wanted to go with the subdomain route, we could have any page offer the "Read in Spanish/English" button that will actually link to the same page on the other subdomain, and that will effectively switch the user over to the other site. Then the "global" language switch (the flags in your example) could just point to the root URL always, which shouldn't be a big deal.

Regarding the example you linked that contains everything in a single site, yeah, that's more or less what I was trying to replicate with my site. I can see you've used some javascript to modify the navbar links depending on the `lang` parameter, which is saved using the `Web Storage` API, right? Hadn't thought of that workaround. I understand this kind of javascript does require premium too, right?

Regarding the subfolder support, are you thinking of allowing different pages within the same site stored in subfolders? Or allowing us to create completely separate sites contained in different subfolders? Or perhaps both :)

The advantage of allowing the creation of a whole new site under the `/en/` subdomain would be that the navbar would work properly without any tweaks, which would be great. I could for instance publish my Spanish site in the root `/` URL, and my English site under the `/en/` subfolder, and everything would just work.

Meanwhile, allowing us to just publish individual pages under subfolders within the same site wouldn't be as good for multi-language sites, as you'd still need to do some custom scripting to handle the navbar. But it would be great for general site organization. For instance, I could have all the content related to ProjectA under `mysite.com/ProjectA/***`, which is a lot more intuitive for visitors than having all the pages hanging off the root folder.

**Comment by HermanMartinus** [comment]
- The JS is nice, but not necessary. I use it to select which homepage and nav to display, but a simple switcher could just be a manual link. 
- Currently Bear doesn't support pathing and folders, but I am considering it. 
- There are no page lists, only post list. Pages explicitly don't show up on feeds since that's not the nature of a page, but the nature of a post. I suggest pages you want on a feed to just make them posts.
