### ISSUE TITLE
Embedding audio

### ISSUE THREAD

**Issue by jessebrennan** [HermanMartinus/bearblog#142]
First of all, this is an awesome project!! I appreciate the simplicity and how easy it is to use.

I would love to be able to embed audio files on some pages. Perhaps the easiest way to do this would be to allow iframes from Soundcloud for example, as in #104.

Another option, which wouldn't require an account with Soundcloud would be to allow HTML audio tags so that we could host our own audio files elsewhere. If your into that idea, than allowing video tags would also be nice.

If you're into either of these ideas, I'm happy to look into making a PR! Thanks for your time.

**Comment by HermanMartinus** [comment]
I've whitelisted Soundcloud 0cd35f77a52c3a5b35cf2a3e2b401f50d79b2564

I'll make a note for adding html audio in the future :)
