### ISSUE TITLE
Another page like blog

### ISSUE THREAD

**Issue by rishyak** [HermanMartinus/bearblog#143]
I want another page like "blog" on my website but I can't seem to figure out how. 

To elaborate, I want something that will catalogue articles in the same format: date, hyperlinked title.

Can I do that?

**Comment by mbluelander** [comment]
Nope, `/blog/` is the only page that works like that, but you could create a different catalog by using tags. For example, if you want to highlight a collection of food-related pages, you can tag a number of blog entries and/or standalone pages with `#food`, then put a link in the header to `/blog/?q=food`

**Comment by HermanMartinus** [comment]
As stated above. You can categorise posts with tags then have a link to a filter of the blog page. 
The other option is for you to curate a page for yourself and just add them as:
```
- *22 Jun, 2022*  Title of article
- *22 Jun, 2022*  Title of article
- ...
```
