### ISSUE TITLE
Add dynamic social preview images for articles link

### ISSUE THREAD

**Issue by tzvc** [HermanMartinus/bearblog#144]
Hey there,

Just started using Bearblog and I love it! I noticed that when sharing an bearblog article link on any social platform, there is no social preview (or just the first photo if the article contains photos).

<img width="607" alt="Screenshot 2022-05-26 at 22 36 38" src="https://user-images.githubusercontent.com/14275989/170937348-77d5059a-2449-4076-8943-33437c7ebb86.png">

I recently worked on a [web service](https://snaplink.dev) to easily create and serve dynamic social preview images by generating them on-the-fly from an HTML/CSS template.
Just design the template with HTML/CSS and {{variables}}, then get a generated link to put in your website `<meta property="og:image"/>`.

I wrote [an example template](https://snaplink.dev/19320d1767?title=How+to+procrastinate&date=16+Jun%2C+2020&subtitle=I+want+to+write.+I+feel+like+I+can+write+well+enough%2C+and+that+I+have+some+fairly+novel+ide...&blog_name=%E1%95%95%28+%E1%90%9B+%29%E1%95%97+Herman%27s+blog&w=1200&h=630) for bearblog. Using the generated link from this template, all bearblog article social preview images would instead look like this:

<img width="593" alt="Screenshot 2022-05-26 at 22 38 31" src="https://user-images.githubusercontent.com/14275989/170938104-a2179993-537c-407c-bfbf-a509395f67c0.png">

Let me know what you think @HermanMartinus, happy to help with anything to make this happen ;)

**Comment by HermanMartinus** [comment]
This would be awesome. I'm focussing on a few longevity things at the moment (trying to make sure that Bear outlives me) then will take a look more deeply into this.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
