### ISSUE TITLE
og:url points to blog homepage, not individual posts

### ISSUE THREAD

**Issue by kixiQu** [HermanMartinus/bearblog#146]
https://github.com/HermanMartinus/bearblog/blob/47d622cbe1fbd5161942ff9ebb79ebd7e331f8e0/templates/snippets/seo_tags.html#L10

https://ogp.me/#aidmetadatahrefmetadatabasicmetadataa

Sample: https://bluelander.bearblog.dev/garbage-digest-01-11/ has `<meta property="og:url" content="http://bluelander.bearblog.dev">` which means link preview generation won't point to the intended content.

**Comment by HermanMartinus** [comment]
Good spot, I'll post an update soon

**Comment by HermanMartinus** [comment]
fixed in 49e335b969b63a177607f28a7e6d5c4f435850e3
