### ISSUE TITLE
Style the tags

### ISSUE THREAD

**Issue by tsangiotis** [HermanMartinus/bearblog#148]
In order to style the tags a class placeholder can be set. This is already available now in the `blog-posts` section, `title` and others.

e.g:

```html
<small>
  <div class="tags">
    <a href="/blog/?q=python">#python</a>
    <a href="/blog/?q=html">#html</a>
    <a href="/blog/?q=django">#django</a>
    <a href="/blog/?q=til">#til</a>
  </div>
</small> 
```

**Comment by HermanMartinus** [comment]
Added `class="tags"` on both post and posts templates 👍 

87c724aaf61a7bd74cf340eca7a740497630e88b
