### ISSUE TITLE
Not able to verify domain via google search console

### ISSUE THREAD

**Issue by ellispinsky** [HermanMartinus/bearblog#149]
Have tried DNS record, and adding HTML tag on meta portion... to no avail.

**Comment by HermanMartinus** [comment]
I've responded in the emails you've sent me, but I'll clarify here for anyone trying to do the same thing. 

The correct way to verify your domain on Google Search Console is by setting a TXT record to the value provided by Google in Ownership Verification Settings. If this isn't working then the DNS records are not being set correctly and this needs to be rectified with the DNS provider. 

In the future Bear will support custom meta tags, but this is not an immediate solution to the problem.
