### ISSUE TITLE
Posts: Preview

### ISSUE THREAD

**Issue by ztheory** [HermanMartinus/bearblog#15]
Hello,

Excellent project/idea. Thank you!

It would be nice to have a "Preview" button/view, so we can see how our posts will look with markdown before they get published.

I can already see myself clearing CloudFlare cache because I find a mistake after I already published a post :)

**Comment by HermanMartinus** [comment]
Cloudflare shouldn't give you an issue with this I think. All of the blogs are currently routed through cloudflare at the moment. 

That being said, I do plan to add a Preview button ;)

**Comment by HermanMartinus** [comment]
@ztheory I've just pushed preview functionality. If you create a post and have the `Publish` checkbox unchecked, once you save it will create a preview link for you (shown where `View Post` generally is). 

Thanks for the suggestion!

**Comment by HermanMartinus** [comment]
Resolved https://github.com/HermanMartinus/bearblog/commit/bbf2eecda7cdd64dc76bec98d7fecc1c7a74e627
