### ISSUE TITLE
Bear is down

### ISSUE THREAD

**Issue by HoangTuan110** [HermanMartinus/bearblog#150]
Bear is currently down (i.e. throwing an error) at the moment. Likely due to huge influx of traffic.

![Screenshot_20220626-065814](https://user-images.githubusercontent.com/66067893/175794049-552c2fd1-b692-4aa9-988b-ff8f990e2bd8.png)

**Comment by HoangTuan110** [comment]
Bear is up now!

![Screenshot_20220626-090645](https://user-images.githubusercontent.com/66067893/175796341-d4c58158-d799-4d9e-95fb-0d17a6fc09a8.png)

**Comment by HermanMartinus** [comment]
Heh, yeah. I just upgraded the dyno to something a bit more beefy. It's weathered 6 HN front-page posts in the past month but this one somehow had a huge influx of people.

I'm working on getting a load-balancer up and running as well.
