### ISSUE TITLE
Data URLs unsupported?

### ISSUE THREAD

**Issue by hamelin** [HermanMartinus/bearblog#155]
When I attempt to embed figures and objects through [data URLs](https://datatracker.ietf.org/doc/html/rfc2397), the data URL gets removed and replaced with `#harmful-link` when previewing the rendering of the post. Are data URLs unsupported by policy, or is that a quirk of the input sanitization process?

Example: the Markdown input is

```
![With data URL](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCI+CjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjUwIiBmaWxsPSJyZWQiIC8+Cjwvc3ZnPg==)
```

The expected output is:

```
<img alt="With data URL" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCI+CjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjUwIiBmaWxsPSJyZWQiIC8+Cjwvc3ZnPg==">
```

The actual output:

```
<img alt="With data URL" src="#harmful-link">

**Comment by HermanMartinus** [comment]
Sorry for only getting to this now. Bear sanitises data urls since it essentially turns the database into (in this case) image storage (which leads to a bigger, more bloated DB). It's better to include images via a link where they can be put behind a CDN.
