### ISSUE TITLE
Replacing deprecated <content>

### ISSUE THREAD

**Issue by HoangTuan110** [HermanMartinus/bearblog#156]
Bear is using the `<content>` tag when rendering the main page content, which is [deprecated according to the MDN.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content)

**Comment by hexpunk** [comment]
If I'm reading MDN correctly, this was never a valid use of `<content>`.  That tag was meant to be used in a shadow DOM context only.

**Comment by HermanMartinus** [comment]
Resolved 🤝
