### ISSUE TITLE
Fathom integration doesn't work

### ISSUE THREAD

**Issue by oluoluoxenfree** [HermanMartinus/bearblog#157]
Get an error when using it as directed:

<img width="814" alt="Screenshot 2022-07-20 at 03 04 08" src="https://user-images.githubusercontent.com/3077443/179880078-91407075-89d3-46a0-adbc-ff3b50688337.png">

**Comment by HermanMartinus** [comment]
This means that the fathom script isn't being retrieved. It's probably working, through, and is being blocked by an adblocker extension in your browser.

**Comment by oluoluoxenfree** [comment]
Ahhhh, thanks so much! Sorry for not checking!
