### ISSUE TITLE
Can't access dashboard via custom domain

### ISSUE THREAD

**Issue by Steellow** [HermanMartinus/bearblog#162]
My domain (https://hanki.dev) works flawlessly for the blog. However lately for some reason I haven't been able to access the dashboard via hanki.dev (https://hanki.dev/dashboard), but I can access it via bearblog.dev (https://hanki.bearblog.dev/dashboard). I get some "form timed out" error

![](https://i.imgur.com/7NKTFQ4.png)

Reloading doesn't work, clearing cookies doesn't work. I've tried on both Chrome and Firefox on 2 different laptops

Any idea what causes this or how to fix it?

**Comment by HermanMartinus** [comment]
I'll take a look into it this week. Thanks for the report 👍

**Comment by HermanMartinus** [comment]
Can you confirm that this was ever working on your custom domain?

**Comment by Steellow** [comment]
Yep, was working just fine before. Last month the whole domain stopped working (something about SSL, can't remember, I changed some settings on Cloudflare which fixed it) but I'm not sure if the dashboard broke then or even earlier

**Comment by HermanMartinus** [comment]
Hmmm, cause it shouldn't have been working on custom domains before hand. What you're getting is a CSRF error in that a domain that isn't whitelisted by Django can't make POST requests (like login). I did, however, set up a reverse proxy to automatically handle SSL certificates about 2 months ago, which could have changed it for you. 

I'm going to dig into this a bit more and see if I can figure it out. In the meantime you can use the dashboard on https://bearblog.dev/dashboard or https://subdomain.bearblog.dev/dashboard

**Comment by HermanMartinus** [comment]
[This](https://stackoverflow.com/a/70689561/5935816) looks promising.

**Comment by Steellow** [comment]
Saw your latest commit, still doesn't seem to work

**Comment by HermanMartinus** [comment]
This took a lot of work to figure out, but it's resolved. Your dashboard should be available at your custom domain once more without any CSRF issues.

**Comment by Steellow** [comment]
Seems to be working, thanks!
