### ISSUE TITLE
Hide Blog name from article/post view

### ISSUE THREAD

**Issue by avinashkanaujiya** [HermanMartinus/bearblog#163]
Hi, thanks for your hard work, I really apreciate it.

I just to wanted ask is it possible to hide blog name from article view?, if not can you make it possible ?

**Comment by HermanMartinus** [comment]
When you set `is_page` to false it will hide the title

**Comment by HermanMartinus** [comment]
Alternatively in your post content you can add `<style>main>h1{display:none}</style>` and it will hide it.

**Comment by avinashkanaujiya** [comment]
> When you set `is_page` to false it will hide the title

It is not working in my post.
Whenever I am adding it to front matter & clicking on Save as Draft, it disappears on next load.

**Comment by avinashkanaujiya** [comment]
> <style>main>h1{display:none}</style>

Doing this hides the post title not the blog title, but I think, I can make it work.

But `is_page` option is not working for me. Maybe a bug?

**Comment by HermanMartinus** [comment]
Sorry, my mistake. Set `is_page` to `true` 😵‍💫

**Comment by avinashkanaujiya** [comment]
Now it is working, but it hides post title & not blog title.

**Comment by HermanMartinus** [comment]
If you want it to hide the blog title as well `<style>h1{display:none}</style>`

**Comment by avinashkanaujiya** [comment]
Thank got for help, got what I wanted.
