### ISSUE TITLE
Modify the new post template

### ISSUE THREAD

**Issue by avinashkanaujiya** [HermanMartinus/bearblog#164]
I want to know how do I update the template of new post, which at the moment shows the markdown syntaxes.

**Comment by Steellow** [comment]
+1, would love to add an "email me" link at the bottom of each post

**Comment by HermanMartinus** [comment]
I've added a way to edit the post template. There's now a button in your posts list on your dashboard with the title `Edit template`. Let me know if you run into any issues with it :)

**Comment by avinashkanaujiya** [comment]
Thanks, will check it out.
