### ISSUE TITLE
Add favorite blogs to follow within the BearBlog discovery feed

### ISSUE THREAD

**Issue by fr0gs** [HermanMartinus/bearblog#168]
It would be nice to be able to follow specific blogs hosted in BearBlog and access them in a new **Favorites** tag in the dashboard  for example. 

It can be easily done having a Page and linking the blogs like: [https://michaelhly.bearblog.dev/my-favorite-bear-blogs/](https://michaelhly.bearblog.dev/my-favorite-bear-blogs/) but a Favorites page would be private.

**Comment by HermanMartinus** [comment]
The ideal way to handle this would be to use an RSS reader ;) but I understand that not everyone is as old-school as me. I'll give it some thought

**Comment by fr0gs** [comment]
Hello, yes indeed that is possible too :) the idea for a Favorites tag is to follow authors you like within the ecosystem directly from the platform, much like Medium does. 

Thank you for the consideration

**Comment by avinashkanaujiya** [comment]
But at the same time, we should try not turn bearblog into another medium, just try to
keep the experience of independent blogging intact.

**Comment by HermanMartinus** [comment]
On further consideration, as nice as the idea of following blogs on-platform is, it does have the tendency to create a highly-coupled ecosystem. Bear is first and foremost a simple blogging platform and I'm hesitant to add social features for fear or deviating from that ideal. 

Due to this I'm not going to be incorporating this feature and would suggest using the RSS feeds :) 

I've also moved all feature requests to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.

**Comment by Yolakalemowa** [comment]
> On further consideration, as nice as the idea of following blogs on-platform is, it does have the tendency to create a highly-coupled ecosystem. Bear is first and foremost a simple blogging platform and I'm hesitant to add social features for fear or deviating from that ideal.
> 
> Due to this I'm not going to be incorporating this feature and would suggest using the RSS feeds :)
> 
> I've also moved all feature requests to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.

Hi Herman, 

Thank you for an awesome service. Excuse me I'm a bit of a noob, but I created a blog and my wife and family want to subscribe to it. Is the only way for them to do that by RSS? I have to find them an RSS reader and teach them how to do it? :') 

They can't subscribe by their emails as usual right? 

Just trying to understand. 

If I understood right, don't you think this makes the blog limited to those with tech know how enough to know about RSS feeds and readers, etc..?

Lastly, do you happen to know of RSS readers that support push notifications? cause until now I haven't found any. 

I hope this is the right place to ask at least the first couple of questions. Thank you so much Herman

**Comment by fr0gs** [comment]
If it's just a small group of people, as stated here : https://docs.bearblog.dev/sending-emails/ you can create your email list and copy/paste the post in the email sending service  and do a batch send to all your subscribers.

**Comment by HermanMartinus** [comment]
@Yolakalemowa as Esteban commented above, you can definitely just run a small email list and send a notification to your recipients. Alternatively there are a decent few RSS readers that support push notifications. I personally use Reeder (although this is Apple specific). I know Feedly is a generally recommended free one.
