### ISSUE TITLE
Error 1016: Origin DNS error

### ISSUE THREAD

**Issue by HoangTuan110** [HermanMartinus/bearblog#169]
Right now, every time someone visits Bear (or one of its website with the .bearblog.dev subdomain) will be reported by a error from Cloudflare. This does not affect websites with custom domains, however.

![Screenshot_20220824-063233](https://user-images.githubusercontent.com/66067893/186284160-d6a8c4e7-3666-48a9-b6a4-611bc90d6172.png)
![Screenshot_20220824-063453](https://user-images.githubusercontent.com/66067893/186286271-31e6b6a1-e435-4f0f-b80c-54b6bd92414c.png)

**Comment by HoangTuan110** [comment]
The problem seems to have been fixed. Issue closed for now.

**Comment by HermanMartinus** [comment]
It looks like Cloudflare was down for a bit sometime last night. I only received the notifications this morning. It looks like an isolated incident and hopefully Cloudflare have resolved it permanently.

<img width="651" alt="Screenshot 2022-08-24 at 09 07 18" src="https://user-images.githubusercontent.com/26326265/186353453-62288cd7-2d93-40f6-a737-569eeab9daaf.png">

**Comment by HermanMartinus** [comment]
It turns out it wasn’t Cloudflare but Heroku which had downtime. Will be moving server providers soon (it has been on the roadmap for a while but I lacked the urgency). https://status.heroku.com/incidents/2453
