### ISSUE TITLE
The new Post is not saved

### ISSUE THREAD

**Issue by win32nipuh** [HermanMartinus/bearblog#17]
I try to create a new post, add title, content, click Save and when I go to Posts I see... nothing.

**Comment by HermanMartinus** [comment]
Hmmm, I can't recreate your issue. 
https://herman.bearblog.dev/this-is-test/
What's the structure of your permalink? Maybe it's a permalink validation issue that I haven't caught

**Comment by Oleg26Dev** [comment]
May be it is permalink.
The first time I did not enter the permalink and clicked Save. But then I have decided to add permalink and Save it again. 
Now I have added on other PC and it works, Thanks.
