### ISSUE TITLE
Custom favicons not working on Safari & Firefox

### ISSUE THREAD

**Issue by Steellow** [HermanMartinus/bearblog#170]
Just noticed that favicons aren't working anymore, every blog is showing the default bear favicon

**Comment by HermanMartinus** [comment]
I assume you're using Safari? It looks like Safari doesn't handle SVG favicons so falls back to the default .ico

They are pulling through for me on Chrome though. Will give this a think

**Comment by HermanMartinus** [comment]
Looks like this is the case. https://caniuse.com/link-icon-svg

**Comment by Steellow** [comment]
Using Firefox version 104.0

**Comment by HermanMartinus** [comment]
Ah, just downloaded Firefox to check. I see what you mean. Will investigate

**Comment by HermanMartinus** [comment]
Fixed for Firefox in 9f545b7e75049a5542e8d4cff19c81ecd67d4b12

Looking into a workaround for Safari

**Comment by HermanMartinus** [comment]
Safari currently doesn't support this but is inevitably going to in an upcoming release. I'm going to close this issue as done and at some point it'll just start working on Safari (maybe).
