### ISSUE TITLE
mistune updated to buggy version

### ISSUE THREAD

**Issue by mbluelander** [HermanMartinus/bearblog#172]
https://bluelander.bearblog.dev/markdown-test/

`This is *italics*, this is **bold**`

parses to:

`<p>This is <em>italics<em>, this is **bold</em></em></p>`

See https://github.com/lepture/mistune/issues/312#issue-1304973034. This seems to have been fixed in 2.0.4.

**Comment by HermanMartinus** [comment]
Sorted in 71f82e01d962e2165927a00e2492025b07bcfa7d

Thanks for the report
