### ISSUE TITLE
custom 404?

### ISSUE THREAD

**Issue by yffr** [HermanMartinus/bearblog#176]
just wondering why this is basically the only part that can't be customized (out of what i've found thus far) - would love to match the fonts and background atleast

**Comment by HermanMartinus** [comment]
This is a fair request. I'll add it to my list :)

**Comment by HermanMartinus** [comment]
Completed in d098226c404c052fa1acd5e86e6a87a9de9699f4

It will now match your custom styles and you can write CSS specifically for the 404 page with the `.404 {color: blue;}` selector.

**Comment by yffr** [comment]
any way to customize the 404 "take me back" link? my blog is more or less a direct link only, displaying the same 404 on the homepage - so, i'd like to also set the blog's 404 page link to my main site, rather than to what looks like the same page again

**Comment by yffr** [comment]
thanks for that quick update btw, it looks so much better matching the rest of the site

**Comment by yffr** [comment]
also noticed that under the `nav` tab in the dashboard, the example links all work except one at the end, its missing [ square brackets ] - just thought i'd let you know

**Comment by HermanMartinus** [comment]
Nice catch on the nav links. I've sorted it out. As for custom redirect for the blog, can you send me an email with your blog domain. It shouldn't 404 on your homepage :/

**Comment by yffr** [comment]
fixed the 404 on the homepage - sorry for not responding for a while...
i have `.404{background:#191724!important}` on my styling page but the 404 remains the same (main website has same background color so no colliding factors as far as i can tell)
any solutions?

**Comment by HermanMartinus** [comment]
Eerp. Looks like post aliases threw this out of whack. Reopening the issue to remind myself to patch this.

**Comment by HermanMartinus** [comment]
Been a wild month so I only got to this now. Custom styles are back online.
