### ISSUE TITLE
Add Support for Scientific Notation Using KaTeX or Whatever

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [HermanMartinus/bearblog#177]
Some bloggers might want to add some math/scientific notation, and there's no option but to take "screenshots" and put the formula or equation as an image. KaTeX claims to be faster and can also be easily self-hosted. For minimalism purposes, you can add a per-post header option such as `use_katex` which can be either `True` or `False`, thus preventing all posts from loading the script. Learn more about [KaTeX](https://katex.org/).

**Comment by HermanMartinus** [comment]
It's something I've been considering for while, but has the potential to add a lot of complexity to what is ostensibly a simple system. Every new feature comes with baggage ;) 

In the meantime, you can add scientific notation with upmath as described in [the docs](https://docs.bearblog.dev/mathematical-notation/).

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
