### ISSUE TITLE
"Made with Bear" footer not centered in Sakura theme

### ISSUE THREAD

**Issue by KensingtonOscupant** [HermanMartinus/bearblog#178]
Title, it's left-aligned I think. I love the themes btw, it's so great to see this project grow :)
Edit: It's the same for the Plain HTML, Sakura Vader and Water themes.

**Comment by HermanMartinus** [comment]
Thanks @KensingtonOscupant I'll sort these out soon. The Sakura and Water themes are external stylesheets which I'm planning to Bear-ify over the next week.

**Comment by HermanMartinus** [comment]
All done (although I'm leaving the Plain HTML one left aligned as it's "plain html") :)
