### ISSUE TITLE
Allow embedding Office files hosted in OneDrive

### ISSUE THREAD

**Issue by Disil** [HermanMartinus/bearblog#184]
It would be great if `<iframe>` for onedrive.live.com is whitelisted, because it allows us to embed word/excel/ppt in post, without hassle (if you have ms account). 

Example of code:
`<iframe src="https://onedrive.live.com/embed?cid=5418DAE1F9C38EFB&resid=5418DAE1F9C38EFB%21365&authkey=ALiwZNmjNH493f4&em=2" width="640" height="480" frameborder="0" scrolling="no"></iframe>`

**Comment by HermanMartinus** [comment]
I've added it to the whitelist 👍
