### ISSUE TITLE
Alphabetize tags

### ISSUE THREAD

**Issue by Steellow** [HermanMartinus/bearblog#185]
You can see a list of tags at the bottom of /blog page. It would be cool if they're alphabetized, or sorted in some logical way.

**Comment by Disil** [comment]
Agreed. Ability to hide the tags would also be great, as a lot of tags will clutter your blog.

**Comment by Steellow** [comment]
Related to this, it would also be cool to be able to find the tag page from Google search, like this:

![Tag search result](https://user-images.githubusercontent.com/20144380/190962023-b8f81b91-5224-4cca-b5f8-d675553c3f5f.png)

And it'd be even cooler if you could add description to a tag, which is shown when you view posts with x tag and would work as a meta description for search engine results.

**Comment by Steellow** [comment]
> Agreed. Ability to hide the tags would also be great, as a lot of tags will clutter your blog.

You could achieve this with a simple `display: none;`

**Comment by HermanMartinus** [comment]
I've alphabetised the tags on the blog page 👍

The searching by tags on google is an interesting idea. I've added it to my list of things to consider for future development
