### ISSUE TITLE
Password Protected Page

### ISSUE THREAD

**Issue by kangminsukdotcom** [HermanMartinus/bearblog#186]
Would be great if there's an option to enable password protected posts/pages. :)

**Comment by Cwpute** [comment]
How would you use it ?
Is it something you want to preview for some people only befire making it public ? Is it articles you only want some people to see for business reason or something ?

Would you be satisfied with having the option to have unlisted articles, that don't show up in your Articles section, but are available from the right URL ?

**Comment by Steellow** [comment]
Kinda workaround, but if you set published date into the future you can still access the post via url, but it's not listed on your blog page

**Comment by HermanMartinus** [comment]
Here are some potential solutions (some mentioned above):
- If you set `is_page: true` then it doesn't show up in your blog list yet can be accessed by direct url
- If you have the article saved as a draft, then it is also not publicly available without the direct url + `published` flag

If you can expand on what the use-case would be for password protected pages we can figure out some other solutions :)

**Comment by HermanMartinus** [comment]
Closed due to inactivity.
