### ISSUE TITLE
[Feature request] Several blogs managed from the same account/email adress

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#188]
Hi! First off, i've been using bearblog for two years and it's been a wonderful experience so far. Simple, fast and easy blogging, as promised.
I have one request that would help me manage things around.

I have currently two blogs on Bearblog: one is about a bike-trip i had in France, and a new one about my artistic projects that i've had on hold for a couple of months but i wish to revive soon. Both blogs are written by me, but cover different things, so i couldn't just reuse the old bike-trip blog to post my new stuff. When i created the new blog, i wished i could have created it from the same email adress i had created the first one with. Lucky me, i use AnonAddy that allows me to create email aliases on th fly so i could provide another email adress easily.
I can see this feature being used in similar other cases: for example, a personal blog with thoughts and slices of life, and another blog with technical articles about my job.
You could limit the number of different blogs to 3 in the beginning, and allow more by request. Or allow this feature entirely on request even.

What do you think ? would that be easily doable ? are other users interested in a similar feature ?

**Comment by HermanMartinus** [comment]
It's a bit of a technical rearchitect to make something like this available. I'll leave this issue open to see if there are more people who would find this useful. In the meantime though, it is possible to sign up with an email address and a '+' modifier as Bear will see **herman@example.com** and **herman+1@example.com** as 2 distinct users, but your email provider (at least most of them) will deliver mail sent to either of those to **herman@example.com**.

**Comment by Cwpute** [comment]
> In the meantime though, it is possible to sign up with an email address and a '+' modifier as Bear will see `herman@example.com` and `herman+1@example.com` as 2 distinct users, but your email provider (at least most of them) will deliver mail sent to either of those to `herman@example.com`
Wait really ?? i never knew that, thanks for the heads-up! i'll look into it.

**Comment by gokceozan** [comment]
I'd say this would be a nice addition. Nothing mission critical (for me, at least). But having different accounts for different blogs might become a bit harder to manage in the long run, especially after 2FA integration. You have to juggle multiple emails, multiple passwords and multiple 2FAs.

**Comment by HermanMartinus** [comment]
This is fair. I've added it to my **to-consider-seriously** list 😄

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
