### ISSUE TITLE
[Feature request] Subscribed blogs feed

### ISSUE THREAD

**Issue by powellgatwit** [HermanMartinus/bearblog#189]
Hi there, I love what bearblog is doing and have already donated to keep it going. One thing I wanted to suggest is a "following" feed inside bearblog for blogs you are following. Like the Discovery Feed page but only blogs you have subscribed to. I searched the roadmap and past feature requests to make sure it had not been asked before.

Is this possible, or something you're interested in implementing?

Also, do you accept code contributions? I've never contributed to open source code before but I would love the opportunity to help build this idea, or help with anything else that is needed, instead of just requesting a feature be built

**Comment by HermanMartinus** [comment]
Hey Powell, thanks for the kind words!

This has been discussed [here](https://github.com/HermanMartinus/bearblog/issues/168) (so I am going to close this issue and we can continue the conversation there). The ideal was to subscribe to blogs would be via the RSS feed (as opposed to having to create an account to subscribe). This isn't un unreasonable request, however, and I am thinking it over. I'm leaning away from it though as I do want to keep Bear quite "pure" and I think having followers and subscribers starts to muddy the water (or as someone commented in the other issue "turn it into another Medium". 

As for contributing to the codebase, pop me an email and we can discuss it further :)
