### ISSUE TITLE
Post date is updated on each save/update

### ISSUE THREAD

**Issue by esprimo** [HermanMartinus/bearblog#19]
If I for example were to fix a typo in a blog post I wouldn't expect the date of the post to update and the list of blog posts to be rearranged.

Maybe instead just not show the update date at all and let the author add an "edited" section in the post manually if needed. Or have a separate "updated at" somewhere, but that seems overkill in my opinion.

**Comment by HermanMartinus** [comment]
Good point. I've addressed it here 6235d295bcd336c2be943af0b061fcccc11640b7
