### ISSUE TITLE
Wrong usage of opengraph metas

### ISSUE THREAD

**Issue by derek-zhou** [HermanMartinus/bearblog#190]
This is the opengraph metas of a random bear blog page:
```
<meta property="og:type" content="website">
<meta property="og:site_name" content="Going outside when I am stressed">
<meta property="og:url" content="https://tsk.bearblog.dev/going-outside-when-i-am-stressed">
<meta property="og:title" content="Going outside when I am stressed">
```

As you can see here, og:site_name is set to the same as og:title. According to: [opengraph standard](https://ogp.me/)

```
og:site_name - If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb".
``` 

So it should be the name of the site, not name of the article. Also, og:type should probably by article, not website. The homepage of a blog can be a website.

**Comment by HermanMartinus** [comment]
I'll look into this and patch as necessary this week +1

**Comment by HermanMartinus** [comment]
Fixed in [a534790](https://github.com/HermanMartinus/bearblog/commit/a534790bfafd3f19c561450f9dfaf0e6cbe27cd6)

**Comment by derek-zhou** [comment]
Thanks. One more thing, the canonical link from both `<link rel="canonical" ...>` and og:url are pointing to the url without the trailing slash. However, the feed is pointing to the url with the trailing slash. The url without the trailing slash redirects to with tailing slash, so I think the canonical urls must be the one with trailing slash. Canonical links are no supposed to redirect.

**Comment by HermanMartinus** [comment]
I've updated the canonical and go urls to respect the slashes 👍
