### ISSUE TITLE
Bearblog localization ?

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#192]
So i was wondering if localizing Bearblog would be an interesting idea to any of you ? i'm a french user and i've seen many different languages represented on the public blog posts page.
I've been using Bearblog for almost two years now and would like to recommend it to people around me, unfortunately, it being onyl available in English makes it very hard to promote to those unused with that language. The main reason i use Bearblog over anything is because it's free, easy to use, unbloated and fast to load, and i'd like my peers to benefit from it too !

There are interesting crowdsourced translation platforms available for use to which each of us could work on for our own language. I'm thinking of [Weblate](https://weblate.org/fr/) namely which seems like the go-to solution for this kind of thing. I should add it's hosted freely for FOSS projects, or can be self-hosted for free.

Also, i know Bearblog is set to be a fairly light project, i don't know much about coding, but localization could potentially bring a good bunch of problems around that were not problems to begin with, and the text from localization in itself could inflate the project's size very quickly too, i don't know really.... so maybe this is not the best idea.
Still, i very much believe this would easily make Bearblog a much friendlier place for those unused to English or less tech-savvy users if it was being translated.

**Comment by dldsantos** [comment]
I like the idea of localization, being from Brazil. I post both in Portuguese and English and it would be interesting to be able to offer my blog interface in Portuguese as well.

Also, is there any current plan to allow multi language posts? For example /en/my-new-post and /pt/meu-novo-post? Please advise if I need to open it as a new issue.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
