### ISSUE TITLE
Timestamp in Discovery Feed is initiated by draft save, not publish

### ISSUE THREAD

**Issue by Poecilia** [HermanMartinus/bearblog#195]
I could be wrong about this, but I strongly suspect that the time stamp and order listed in the 'Most Recent' list on the Discovery feed is initiated by the first 'Save Draft' press, and is therefore not an accurate timestamp of when the blog was actually first published.

**Comment by HermanMartinus** [comment]
You're kinda correct. When the "Save Draft" is pressed the `published_date` is created. This can be modified directly before publishing to better reflect the actual publish time. I'll give some thought on how to make this more elegant without adding too much complexity.

**Comment by HermanMartinus** [comment]
After consideration updating `published_date` is the best way to handle this. You can also include time in published date using ISO format.
