### ISSUE TITLE
Adding HTML comments to a post results in Server Error (500)

### ISSUE THREAD

**Issue by yurirenko** [HermanMartinus/bearblog#196]
If you add
```markdown
<!---
-->
```
to a post or Home page, opening that page will result in `Server Error (500)`.

**Comment by HermanMartinus** [comment]
And so it does. Looking into it now.

**Comment by HermanMartinus** [comment]
Resolved in 1ae4ff9a8ac26e9e02b774bafdd44b33c114a445
