### ISSUE TITLE
Title with all characters in CJK generates inaccessible link

### ISSUE THREAD

**Issue by NightFeather** [HermanMartinus/bearblog#197]
I've stumbled upon some pages in discovery and also tried publishing one myself.
I found that if I use only CJK characters in title field, it will generates a empty link, which makes the page inaccessible from public side.

Manual specify a link would solve this, but maybe it should warn user that auto-generated link is empty ?

**Comment by HermanMartinus** [comment]
It looks like the slugification of the title doesn't support those characters. I'll look into some solutions for this, but in the meantime you will have to specify the **link** yourself.

**Comment by HermanMartinus** [comment]
If the link is bad it is auto-generated as a 10 character string. This worked better than encoding as both are unreadable but the auto-generated link is shorter and easier to work with.
