### ISSUE TITLE
RSS / Atom / JSON Feed support

### ISSUE THREAD

**Issue by khm** [HermanMartinus/bearblog#2]
Hi,

I like your project, and I think it's great you're running a service like this.  Please consider adding RSS, Atom, or JSON Feed support -- it makes it easier for people to follow blogs, and it can cut down on bandwidth since popular readers like Feedly can serve tons of subscribers on your behalf.

I think it should work fine to use your existing templating system, just creating a feed template and adding a link rel='alternate' would be enough to get you going.  

What do you think?

**Comment by HermanMartinus** [comment]
Yeah, absolutely! I'm a big fan of RSS feeds. It's on my list.

I'm glad you're enjoying my weekend project :)

Herman

**Comment by DivisionMax** [comment]
@HermanMartinus https://docs.djangoproject.com/en/3.0/ref/contrib/syndication/

**Comment by HermanMartinus** [comment]
Feeds are now available at `/feed` eg: herman.bearblog.dev/feed or wordbutter.online/feed

**Comment by khm** [comment]
Looks good!  I'd consider making it configurable for the person to put a contact address where it's currently hardcoded to 'hidden', but that's your call and otherwise this is great!

**Comment by manton** [comment]
I added issue #35 about a few things to fix in the feed. Also, JSON Feed support would be great! Since you have `/feed`, you might consider `/feed/json`, since both would be consistent with WordPress for example.
