### ISSUE TITLE
Custom domain option missing

### ISSUE THREAD

**Issue by bryanroth** [HermanMartinus/bearblog#20]
According to the documentation for [custom domains](https://github.com/HermanMartinus/bearblog/wiki/Custom-domains), there should be an option to specify a custom domain but I am not seeing this option:

![image](https://user-images.githubusercontent.com/183269/83336722-678a1080-a27b-11ea-9de9-df97d4e7fd32.png)

**Comment by HermanMartinus** [comment]
Hi @bryanroth, add a title and subdomain to the blog first, click save, then you can add the custom domain :)

**Comment by bryanroth** [comment]
Ah, there it is. Thank you, Herman!

**Comment by sreekar2298** [comment]
Hi, @HermanMartinus. I'm facing a similar issue. I can't find the custom domain settings in the bearblog dashboard. And even if I add a title and subdomain, I'm not able to connect my domain. 

![Screenshot 2023-07-15 at 6 34 58 PM](https://github.com/HermanMartinus/bearblog/assets/133399421/8613733c-4bb4-4c7f-9dea-b77981afdd96)
