### ISSUE TITLE
Post is not visible in feed

### ISSUE THREAD

**Issue by fuiomnia** [HermanMartinus/bearblog#201]
Hey, I published a post and the make discoverable is set to true but the post is not shown in most recent posts in feed, what did I do and what to do to fix it? Thanks

**Comment by HermanMartinus** [comment]
The post will only show in the feed once the blog has been reviewed (this is to keep Bear spam free). I review all the new blogs a few times a week. 

You can read more about it here: https://docs.bearblog.dev/review-process/
