### ISSUE TITLE
[Feature Request]Bookmark cards?

### ISSUE THREAD

**Issue by gokceozan** [HermanMartinus/bearblog#205]
Is it possible to have a "bookmark card" style linking option? Something similar to what other blogging software has.

If it complicates things even without a screenshot image. It would help to make a certain link appear more "block-like". Would also make "link post" and "reading list" style posts more appealing.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
