### ISSUE TITLE
Embed music file? Discoverability of a blog?

### ISSUE THREAD

**Issue by dmt-hub** [HermanMartinus/bearblog#208]
Would love to have the option to embed music/mp3 via this code -> "audio src="/path/to/audio.mp3"></audio"

And by discoverability, does this mean every post someone makes will appear in Bear's Most Recent Discovery feed or only random posts make it into the Most Recent discovery feed ?

**Comment by HermanMartinus** [comment]
You can currently embed audio, although it would have to be included from an external source as I haven't built media uploads outside of images yet. You can also embed Soundcloud player.

All your posts are discoverable by default and will therefore show up on the most recent page in the discovery feed, and possibly on the trending page depending on the number of upvotes. If you set **make_discoverable: false** it won't show up on either page. Here are some other options and explanations of how the posts work: https://docs.bearblog.dev/post/

**Comment by dmt-hub** [comment]
Thank you for the information. 
I checked the discoverability and even set it to: true when making a post.
None of my posts ever came up in the recent section of the feed.

**Comment by HermanMartinus** [comment]
This is probably due to it not being reviewed yet (I'm reviewing the new blogs today). This is to prevent spam from finding its way to the discovery feed. You can read more about that here: https://docs.bearblog.dev/review-process/
