### ISSUE TITLE
Fathom script fetched from generic CDN and blocked when using custom domain 

### ISSUE THREAD

**Issue by zengspr** [HermanMartinus/bearblog#209]
I've set up a Fathom [custom domain](https://usefathom.com/docs/script/custom-domains) but it seems that my blog is still fetching the analytics script from the generic Fathom CDN, which is being blocked: 

![CleanShot 2023-01-22 at 11 46 54@2x](https://user-images.githubusercontent.com/58009357/213936971-ea5a7350-8d54-456c-9ec0-7bdded68eb8b.png)

Is it possible to let us choose which CDN we're fetching from?

**Comment by HermanMartinus** [comment]
Thanks for reporting this Spencer. I've added it to my list of things-to-do

**Comment by zengspr** [comment]
Thanks!
