### ISSUE TITLE
Include post title in <title> tag

### ISSUE THREAD

**Issue by esprimo** [HermanMartinus/bearblog#21]
It seems like it would be good for SEO and navigating browser tabs by including the post title in the `<title>` of the page.

Maybe `post.title + " | " + blog.title` so it would end up being eg. `The Hacker News Hug | ᕕ( ᐛ )ᕗ Herman's blog`.

This should probably be a thing for all pages, not just post pages.

**Comment by HermanMartinus** [comment]
That's a very good idea, I'll push an update today

**Comment by HermanMartinus** [comment]
Just quickly did it now cb403e2c77431c1a7b4747043dd2160ae184989e
