### ISSUE TITLE
Blog posts not visible in "most recent" section of the Discover feed

### ISSUE THREAD

**Issue by piyagehi** [HermanMartinus/bearblog#210]
I started a blog four days ago, and there are four posts up so far, one on each day. I've been checking the "most recent" section of the feed after posting and don't see either of the posts there. I've seen quite a few first posts of other blogs in that feed though, so is there some issue with my blog posts which is causing it to not display on the feed? The blog URL is braindump.bearblog.dev

**Comment by HermanMartinus** [comment]
Your blog has not been reviewed yet (you can read more about the review process [here](https://docs.bearblog.dev/review-process/). I review all new blogs 2-3 times a week so yours should be reviewed today.
