### ISSUE TITLE
Recommended source for file links?

### ISSUE THREAD

**Issue by redweezul** [HermanMartinus/bearblog#211]
Hi Herman, many thanks for making such a slick platform.
I'd like to link to a group of files (work examples), in various formats - PDF, HTML, DOCX, etc. I know Bear supports links from OneDrive per a prior issue. 
Should I default to OneDrive for all file storage/links, or use a more Bear-friendly option?
Probably a basic question, but in any case. Thanks.

**Comment by HermanMartinus** [comment]
You can add links to files as a simple link with no issues from anywhere. If you're looking to have it embedded in the page somehow I'd need to whitelist the domain for that iframe. So if you're just looking to make a PDF downloadable you can simple add a `[Download PDF](link-to-uploaded.pdf)`. However if you'd like to embed it as a readable PDF in the page you may have to include it via OneDrive or send me your preferred service and I'll whitelist it :)

**Comment by redweezul** [comment]
Much appreciated Herman. I just wanted to add links to work examples; decided I'd build a small consulting website on Bear! If I can link from anywhere, I'll try OneDrive or here on GitHub.
