### ISSUE TITLE
I am having issues with posting an about page 

### ISSUE THREAD

**Issue by hackmeister** [HermanMartinus/bearblog#212]
I published two pages a home page and an about page. I no longer can see my home page and my about page shows up as my home page. If you could help square this away I would be very happy.
website address:  https://drdoall11.bearblog.dev
email address: drdoall1@gmail.com 

If you should have any questions at all the email address will work.

Thanks
Jim

**Comment by HermanMartinus** [comment]
Hi Jim, I've taken a look at your blog and everything looks fine.
