### ISSUE TITLE
Something went wrong. Try subscribing again. ʕノ•ᴥ•ʔノ ︵ ┻━┻

### ISSUE THREAD

**Issue by jliikala** [HermanMartinus/bearblog#215]
Hi Herman! I think I might have found a glitch in the email subscription process. I think it might have be caused by + character in the email?

- I subscribed via subscribe form on my site with email like someaddress+alias@gmail.com
- I get _confirm your subscription_ email and click the confirm link in the email
- Blog website opens and I see "Something went wrong. Try subscribing again. ʕノ•ᴥ•ʔノ ︵ ┻━┻" error

Other email addresses that I tested with worked as expected. It was the + character one that seem to fail.

Probably not yet a known issue?

Cheers!

P.S. Bearblog seems such a wonderful product. Thanks for making it! :)

**Comment by HermanMartinus** [comment]
Thanks for reporting this. I can't seem to recreate it with my emails using **+** aliases. Could you forward me the broken subscription confirmation email and I'll dig into it and see what may be causing it.

**Comment by HermanMartinus** [comment]
Resolved
