### ISSUE TITLE
[Feature Request] Support for Matomo analytics or Matomo tag manager

### ISSUE THREAD

**Issue by alexlehm** [HermanMartinus/bearblog#216]
I wonder if it would be possible to support Matomo analytics as a configurable option or the tag manager?

This would be less intrusive than google analytics (though you could set up GA with the tag manager as well if you wanted) and would provide nice stats if you already have an instance of Matomo available on another site.

**Comment by alexlehm** [comment]
Though you can do the basic tracking (without JS) using an image tag in the Nav

**Comment by florentdestremau** [comment]
I was about to post the same thing for https://plausible.io/ too, which shares the same lightweight open source philosophy as bearblog.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
