### ISSUE TITLE
Blog header/subtitle?

### ISSUE THREAD

**Issue by redweezul** [HermanMartinus/bearblog#217]
Hello again! Since the blog is auto-generated, there's no 'blog' page per se in Bear. It would be great it we could add a subtitle to a blog...a short description, if you will, which would stay above the posts list.

I don't think such a function exists yet (unless I missed it!). If not, what do you think of adding it? Thanks.

**Comment by HermanMartinus** [comment]
There isn't any explicit functionality built in for this yet. I'll give it some consideration. Here's a workaround though:

At the bottom of your stylesheet add:

```
.blog ul.blog-posts:before {
 	content: 'Here is a collection of my writing, essays, and thoughts';
    font-weight: bold;
}
```

**Comment by redweezul** [comment]
Much appreciated! This drops in perfectly.
