### ISSUE TITLE
Duplicate H1 tags on posts / pages

### ISSUE THREAD

**Issue by jliikala** [HermanMartinus/bearblog#218]
Hi Herman,

I noticed that there seem to be two H1 elements on post / pages layout. The header blog title uses one and also the post title uses it. As far as I know, it's a bad SEO practice to have multiple H1 tags on a page.

Maybe just remove the h1 element from the header blog title entirely or at least remove it when on post / page layout which also uses that element?

Cheers! :)

**Comment by HermanMartinus** [comment]
This has been logged as an issue a few times before. I've dug deep into it and overall it doesn't negatively affect SEO. It may have back when search engines relied on structured data to make sense of a page, but they've become much more advanced of late. 

And while it is against standard there are too many blogs that have their styling set by the h1 element that updating the overall structure of the page would break a lot of people's styling.
