### ISSUE TITLE
Add a images (listing) link to dashboard

### ISSUE THREAD

**Issue by professosaurus** [HermanMartinus/bearblog#219]
Allow to see a list of uploaded images, possibly with preview, from a page linked to by the dashboard page.

It could be useful when reusing images, I think. 

... if I'm not doing some error due to ignorance or little attention by me.

Thanks for this very exact blogging platform, Herman.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
