### ISSUE TITLE
An option to set or edit post date?

### ISSUE THREAD

**Issue by tedmiston** [HermanMartinus/bearblog#22]
Hi - I found Bear via Hacker News.  I have played with it a bit and am really enjoying it.  I am exploring migrating a blog currently on Ghost to it but would like to preserve the existing post publication dates.  Any chance of exposing initially setting and/or editing of this field in the dashboard?

**Comment by HermanMartinus** [comment]
Hey Ted, good plan. I'll add it to the top of my list. Give me a day :)

**Comment by HermanMartinus** [comment]
Addressed in 5965d45d9d0229953fa55569ee9c030626b72a9a

If you have any issues, let me know, else close this issue :)
