### ISSUE TITLE
[Feature request] Send new subscriber info straight to mailing service of choice 

### ISSUE THREAD

**Issue by jliikala** [HermanMartinus/bearblog#220]
It's great that Bear provides an easy way to collect subscribers and have means to import those to external mailing services via export file.

However, it would be even more awesome if I could just hook up the subscribe form in a way that it would automatically send the new subscriber info to the mailing service of your choice. For example, I'd like to send the subscribers straight to my Buttondown mailing list. The form action would just need to be https://buttondown.email/api/emails/embed-subscribe/<myButtondownUsername>.

Buttondown is my favourite, but I bet MailChimp and ConvertKit would be few other popular alternatives.

Is this something that could be considered? 

Thanks! :)

**Comment by HermanMartinus** [comment]
It's been on my list for a while. I just wish that there was a standard for email subscriber webhooks, since each of these services has their own way of doing things, so I'd have to build functionality individually for each service. Will give it some thought :)

**Comment by jliikala** [comment]
Thanks Herman, that would be great! :)

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
