### ISSUE TITLE
Unable to take a one-year subscription

### ISSUE THREAD

**Issue by therealkarnotus** [HermanMartinus/bearblog#221]
Hi,

I love your blogging app !

But my Mastercard is declined when I try to buy a one-year subscription. Is it because I am living in Belgium ?

Kind regards

**Comment by HermanMartinus** [comment]
I've been having an issue with Lemon Squeezy recently :/ Can you please send an email to hello@lemonsqueezy.com reporting this issue. Then send me an email with your blog id (subdomain) and I'll upgrade you and we can sort out payment with Lemon Squeezy figures it out :)
