### ISSUE TITLE
[Feature request] Search box for blog posts

### ISSUE THREAD

**Issue by chalalala** [HermanMartinus/bearblog#222]
As far as I know, Bear Blog already supports filter by blog's tag by adding it to the query params, but haven't had a specific place on site to search for it. Sometimes it could be inconvenient for me to edit the link to search.

So, it would be nice if we could have a search box somewhere, maybe right on the Blog page, before the posts list, to take the query, slugify it (in case the input has some spaces or special characters), and submit to add the filter.

And it'd be more than awesome if we could search by blog's title or content also. But if it takes too much effort, then searching by tag might be good enough.

Thanks for your time!

**Comment by HermanMartinus** [comment]
It's definitely something I'm looking into 👍

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
