### ISSUE TITLE
RSS - wrong site link

### ISSUE THREAD

**Issue by fivestone** [HermanMartinus/bearblog#223]
In rss, the site link is still the url of rss itself, but should be that of the website.

And it would be appreciate if RSS can be placed defaultly in menu bar, so that the subscribers won't need to find it in source code.

Regards,

**Comment by HermanMartinus** [comment]
You can add it to the menu bar by editing your nav and adding `[RSS feed](/feed/)`

I'm not sure if I follow what you mean by the url of rss should be that of the website. Please expand on that and I'll see what's up :)

**Comment by fivestone** [comment]
![image](https://user-images.githubusercontent.com/491300/222055721-a0817f12-a7e6-453f-a95a-1f4a61cdb7f9.png)

**Comment by HermanMartinus** [comment]
Resolved in 8e3d20a65bd90d4d386a557620b9789e404e7ae0
