### ISSUE TITLE
feat: pagination support

### ISSUE THREAD

**Issue by freitzzz** [HermanMartinus/bearblog#225]
cross-issue: https://github.com/janraasch/hugo-bearblog/issues/64

Hi @HermanMartinus :wave: 

First of all, thank you for the initiative of bearblog! Javascript less websites are awesome and should become more popular now that we have the power of SSG engines right in our hands :) This feature comes from `bear` clone with Hugo SSG, which depends on this repo HTML+CSS.

We would love to have support on pagination, especially on list pages where too many nested pages start becoming a mess to visualize. Let me know if it's on `bear` backlog to support such feature and if you have time to work on this. If such, I can help you implementing this feature!

Best regards,
freitzzz

**Comment by HermanMartinus** [comment]
Hey Freitzzz, thanks for the suggestion.

I've recently cleaned out the feature requests from GitHub issues and am reserving this for bugs and problems (just for sanity sake). Could you add your feature suggestion to the [suggestion board](https://bear.nolt.io) (and vote on anything else you think would be cool). Also, please expand on what you're looking to pagenate (from your description I'm assuming it's post content and not the list of posts?). 

Cheers :)
