### ISSUE TITLE
Add 'Discover' (or something) to the title of discover page

### ISSUE THREAD

**Issue by NiloCK** [HermanMartinus/bearblog#227]
bearblog.dev/discover would be easier for me (and maybe others) to navigate to if the page's title included something distinct from the other pages on site.

(my default navigation mode is ctrl+l for location bar, then two or three characters which align with text from previously visited pages titles - firefox filters well on these titles).

Really enjoy the site / project.

**Comment by HermanMartinus** [comment]
Thanks for pointing this out, I've pushed an update :)
