### ISSUE TITLE
It's possible to self-host this?

### ISSUE THREAD

**Issue by vidalpascual** [HermanMartinus/bearblog#23]
Hi!

I would like to self-host this type of blog, giving the proper credit to the developer, of course. It's possible?

I would like to see some brief instructions of how to do it.

Thanks a lot!

**Comment by HermanMartinus** [comment]
It's currently not possible to self-host an individual blog. I am planning on making something like that available in the future, but it's currently not possible.

**Comment by HermanMartinus** [comment]
There is now a Bear Blog theme for Hugo [here](https://github.com/janraasch/hugo-bearblog) by [Jan Raasch](https://www.janraasch.com/)

**Comment by rinukkusu** [comment]
But it should be possible to start up an instance of this bearblog on my own server after some changes, no?
