### ISSUE TITLE
Is this repo currently accepting PRs?

### ISSUE THREAD

**Issue by joshua-mo-143** [HermanMartinus/bearblog#230]
Hey there! I was wondering if this repo is currently accepting PRs as there's currently some open PRs that have been open for some time but not accepted.

If contributions are being accepted, I would not mind writing a draft for a CONTRIBUTIONS.md file (incl. guidelines on perhaps maybe trying to do some testing).

**Comment by HermanMartinus** [comment]
Hey Joshua, contributions aren't being accepted right now. I tried accepting contributions for a bit but most of them (if not all of them tbh) were low effort and a waste of my time. The bulk of them were just trying to show up on the "Contributor" section of Bear and get some Github cred. I've just closed the low effort PRs and will consider merging the rest when I get the chance to give them a proper review. 

My reason for Bear being open source is not necessarily to accept participation in building, but to:
- Make the code available to others for their personal projects, or to satisfy their curiosity
- To ensure that everything is transparent, keeping Bear (the organisation) honest about what it does

Thanks for the offer though! I'll be writing up a Contributions file in the near future better outlining what I've said here :)
