### ISSUE TITLE
Editing a long blog post impossible as location keeps being reset to top when typing

### ISSUE THREAD

**Issue by natmchugh** [HermanMartinus/bearblog#232]
Recent changes to the editor have made editing long posts impossible
See screen recording:
![bear](https://github.com/HermanMartinus/bearblog/assets/191565/32e957ee-9e1d-412a-84f9-ee0b43f8f3d3)

**Comment by HermanMartinus** [comment]
That was my fault. I've fixed the offending code and will re-look at the issue in the morning. 

Sorry for the inconvenience!

**Comment by natmchugh** [comment]
No worries thanks for looking into  the issue.
