### ISSUE TITLE
Text editor doesn't work well

### ISSUE THREAD

**Issue by therealkarnotus** [HermanMartinus/bearblog#233]
The new version of the text editor doesn't allow the processing of header information.

![Image 17-05-23 à 19 29](https://github.com/HermanMartinus/bearblog/assets/125745125/4864e84b-8701-48f9-9a8d-8eac143143f0)

**Comment by HermanMartinus** [comment]
So I've separated the input area for the header and the content on the post interface.

The reason for this is too many people were removing the `___` and getting confused and submitting broken posts.

**Comment by therealkarnotus** [comment]
Good morning,
Thank you for responding so quickly to my comment.
I understand your decision. I know how to fully use the encoding interface again. I was amazed at this change; I thought there was a problem but it wasn't
Thank you,

**Comment by HermanMartinus** [comment]
I've modified the code for the post template as well, so your original post template should still work now :)
