### ISSUE TITLE
W3C validator shows some errors

### ISSUE THREAD

**Issue by eklausme** [HermanMartinus/bearblog#236]
Not a big issue in any way, but hopefully worth noting.

Checking [Herman's blog](https://herman.bearblog.dev/blog/) with [Nu HTML Checker](https://validator.w3.org/nu/?doc=https%3A%2F%2Fherman.bearblog.dev%2Fblog%2F) shows some errors like:

> Error: Element [style](https://html.spec.whatwg.org/multipage/#the-style-element) not allowed as child of element [footer](https://html.spec.whatwg.org/multipage/#the-footer-element) in this context. (Suppressing further errors from this subtree.)

or

> Error: CSS: border-image: Parse Error.

or

> Error: Attribute pubdate not allowed on element [time](https://html.spec.whatwg.org/multipage/#the-time-element) at this point.

There are also a couple of info-messages, like

> Info: Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

The error regarding `X-Clacks-Overhead` obviously can be ignored, as this seems to be intentional.

For [bearblog.dev](https://validator.w3.org/nu/?doc=https%3A%2F%2Fbearblog.dev) there is

> Error: Bad value data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐼</text></svg> for attribute href on element [link](https://html.spec.whatwg.org/multipage/#the-link-element): Illegal character in scheme data: < is not allowed.

and

> Error: CSS: Parse Error.

There are other errors in the validator report.

Just for completeness: The mentioned blogs show just fine on Firefox and Chromium. So errors in the validator do not necessarily lead to problems in actual browsers. But usually, for a new blog, you aim to be "validator-compliant".

Thanks for providing [bearblog.dev](https://bearblog.dev).

**Comment by HermanMartinus** [comment]
Yeah, none of these cause any issues, but for brevity I've gone and sorted them all out. All the non-closing tags are up to HTML 5 standard, I've moved Clacks Overhead to middleware, and sorted out the rest of the info and warnings. 

One issue is the `<content>` tag. I've made a note to replace this with `<section>` but will need to programatically update all users' custom styling just in-case they use `<content>` as a selector.
