### ISSUE TITLE
plain text pre?

### ISSUE THREAD

**Issue by Nakilon** [HermanMartinus/bearblog#237]
https://herman.bearblog.dev/markdown-cheatsheet/

I tried formats `none`, `text` and `plain` -- all they highlight words "for", "static", "and", "in"

[example](https://nakilon.bearblog.dev/split-and-automate/)

**Comment by Nakilon** [comment]
I see no space
![image](https://github.com/HermanMartinus/bearblog/assets/2870363/6c97fefe-5da7-49c7-ab81-c43c1cbeeb19)
not even non-printable -- I move the cursor char by char and there is nothing in between.

**Comment by HermanMartinus** [comment]
Huh, thanks for letting me know. I'll look into it :)

**Comment by Nakilon** [comment]
> When I changed none to text and pressed "View" it was colored. But when I pressed Publish, now colors are gone.

There is a possibility that I really pressed "View" while in fact you have to press the "preview" button at the bottom.

**Comment by HermanMartinus** [comment]
That's not a bad idea. I'll give it some thought. Thanks for the suggestion 👍
