### ISSUE TITLE
rate limiting on blog posts

### ISSUE THREAD

**Issue by martinmckenna** [HermanMartinus/bearblog#238]
hi!

i think there should be a rate limit on publishing posts. on more than a few occasions, the recent feed (which i like reading almost every night) gets junked up by someone publishing stream-of-consciousness posts that bloat up the feed that have essentially zero substance.

maybe like 2-3 per day would be nice

**Comment by HermanMartinus** [comment]
Ah, I see what you mean. Instead of a rate-limit (which imposes restrictions on the way that people can use the platform) I'm instead going to create a moderation tool that hides blogs that do this from the discovery feed.

**Comment by HermanMartinus** [comment]
The offending site has been hidden from the discovery feed. Please report sites to abuse@bearblog.dev and I'll review and update the moderation.
