### ISSUE TITLE
auto-save feature?

### ISSUE THREAD

**Issue by Yolakalemowa** [HermanMartinus/bearblog#240]
Hello,

Do you think it would be possible/good to make drafts autosave after every change? You know how google docs and other platforms have. It sucks to be writing a long blog and then something happens to the page and I lose everything and have to start again.

Not sure how feasible. But would certainly be a great feature to have.

Thank you and appreciate the good work :)

**Comment by HermanMartinus** [comment]
Thanks for the suggestion. I've added it to the feature request board (the GitHub issues are for bug reports). 
https://bear.nolt.io/103

You can vote on it and other issues on the feature request board :)
