### ISSUE TITLE
feature request: Schedule posts

### ISSUE THREAD

**Issue by fr0gs** [HermanMartinus/bearblog#241]
That's it :) I wonder if you're considering the possibility of scheduling a post for a given date. Sometimes I churn two or three posts in a single go and I want to space their publishing.

**Comment by HermanMartinus** [comment]
This feature is currently available. If you set the [published_date](https://docs.bearblog.dev/post/#published-date) to the future it will schedule it. Include the time at UTC and it will publish it then (although you won't see the time on the editor or post). 

Thanks for the suggestion! Please post those to the [feature suggestion board](https://bear.nolt.io) in the future :)
