### ISSUE TITLE
Sign up throws error due to password not adhering to password rules

### ISSUE THREAD

**Issue by pmuens** [HermanMartinus/bearblog#242]
Hey everyone,
I tried to sign up today but can't complete the procedure due to an invalid password. The error message says: "Your password needs a special character, a number, and a capital letter" (see screenshot below).

I'm using the password generator from a password manager and all the passwords I tried had a special character, a number and an uppercase letter in them. Here's one example password I tried: `Q4@&T3&6U2vZqSfJbf$Qkv&TN$DuNq`.

I had a blog before which got deleted. Not sure if that's the issue here.

Thanks a lot for looking into this and let me know if there's anything I can do to help.

<img width="871" alt="Screenshot 2023-07-25 at 8 30 41 PM" src="https://github.com/HermanMartinus/bearblog/assets/1606004/00f1f24c-8865-4b36-bdf6-5557c5107dff">

**Comment by HermanMartinus** [comment]
This is Bear's spam prevention system you're hitting against. If a blog has been removed and if you're having a problem signing up again, it's probably marked your content as spam. Please send me an email with your previous blog subdomain and title and I'll review it and unblock your account.
