### ISSUE TITLE
Unusable line break

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#243]
I like to do line breaks/text wrapping breaks when writing on a keybard, as it helps me format my text in a more readable way. 

Unfortunately on Bearblog, when i press Enter to start typing on a new line, the text editor does not recognize this as valid, and instead throws back my new line of text at the end of the previous line.
If i really want to write from the start of a new line, i have to press Enter two times and start a new paragraph, with no in-between possible.

_See the screenshots below._
In the text-editor:
![firefox_MPf3Gx8fQE](https://github.com/HermanMartinus/bearblog/assets/80604512/61290925-ed72-4bef-b8f6-9312059ca7bc)
Published as an article (don't mind the offset button):
![firefox_02WX844fuP](https://github.com/HermanMartinus/bearblog/assets/80604512/3d723ff2-973d-41b2-9ef8-539e2f5f29a6)

**Comment by Deijin27** [comment]
This line merging is a common feature of markdown.

If you put two spaces at the end of the first line, it will go to the next line without a paragraph break like you want.

**Comment by Cwpute** [comment]
Oh, right, it is, thanks @Deijin27 . Sorry for the inconvenience.
The way it works i find it to be not intuitive, maybe this would be worthy of appearing in the bearblog docs for markdown formatting ?

**Comment by HermanMartinus** [comment]
I've updated the markdown docs to include this 👌
