### ISSUE TITLE
Names of days and months don't change with locale

### ISSUE THREAD

**Issue by patosar** [HermanMartinus/bearblog#246]
Even though I've changed my blog's locale through the *lang* attribute in the main page, all the dates rendered in my blog still show the English names for months or days of the week.

Since I set *lang: es*, it for example ought to render August as "Ago" rather than "Aug".

(My blog is at [fech.cl](https://fech.cl))

**Comment by HermanMartinus** [comment]
Hey @patosar, thanks for pointing this out. I've pushed an update that uses the blog lang to update the date. Please let me know if you run into any issues with it

80c073567344a64f02c13802433f359e3fde1149

**Comment by patosar** [comment]
Many thanks @HermanMartinus! Everything seems to be working ok
