### ISSUE TITLE
ChatGPT blocking with robots.txt?

### ISSUE THREAD

**Issue by bjhess** [HermanMartinus/bearblog#248]
Wondering if you are considering adding ChatGPT blocking with robots.txt?
* https://platform.openai.com/docs/gptbot/gptbot
* https://platform.openai.com/docs/plugins/bot/chatgpt-user

Thank you!

**Comment by HermanMartinus** [comment]
Great idea :) I've just pushed the update.

**Comment by bjhess** [comment]
Ah, thank you, @HermanMartinus!
