### ISSUE TITLE
Feature request - ActivityPub integration

### ISSUE THREAD

**Issue by bernaldobarrena** [HermanMartinus/bearblog#250]
Not sure if this would be desirable, since I understand the need of keeping the code as nice and tidy as possible, but It would be great some kind of integration with ActivityPub.

For your consideration.

**Comment by bernaldobarrena** [comment]
The possibility for others to follow my blog in the fediverse from Mastodon
or other social networks, for example. It is one of it's functions and may
be very practical. However, I understand that we are all about simplicity
here so it is totally fine if not feasible 😊

**Comment by HermanMartinus** [comment]
There have been a decent few votes for ActivityPub integration on the [feature request board](https://bear.nolt.io). Could you please vote and comment your use case there. I like to keep the GitHub issues for bugs and feature suggestions on Nolt so they can be voted on :)
