### ISSUE TITLE
edited post template not applied

### ISSUE THREAD

**Issue by deogracia** [HermanMartinus/bearblog#252]
HI,
Just starting today using Bear. Thanks a lot ^^

I want to use the following post template

```
title: Mon post
link: mon-post
lang: fr
meta_description: If no meta description is set, it will default to the first 160 characters of the content of the post.
tags: posts,writing,2023

---
# Titre
```

Once updated, the new post doesn't use it at all.
![image](https://github.com/HermanMartinus/bearblog/assets/553342/cf00a984-c2c2-4800-b36f-4f2275350341)

I can't find what I did wrong :'( It does the same even when I just use `Title: My post` only.

**Comment by HermanMartinus** [comment]
Hey, so it looks like you're using dashes, where you should be using underscores to separate the post attributes and the content :) `___` vs `---`

It's super subtle and I should emphasise this somewhere.

**Comment by deogracia** [comment]
Damened! 

it really whas me using dashes instead of underscores my issue!
my new example template
```
title: Mon post
link: mon-post
lang: fr
meta_description: If no meta description is set, it will default to the first 160 characters of the content of the post.
tags: posts,writing,2023

___
# Titre
```

And the final result : 
![image](https://github.com/HermanMartinus/bearblog/assets/553342/c5216589-0870-491e-a053-701665934eee)

Thanks a lot :D
