### ISSUE TITLE
Whitelist Openstreetmap

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#253]
As suggested by @davidfromtheworld in issue #247:

> could it be possible to whitelist openstreetmaps (more specifically umap.openstreetmap.fr)? umap is a more privacy-friendly alternative to google my maps that uses openstreetmaps, and i use it to make maps about places i visit for my blog and it would be rather helpful to use it in bear :)

**Comment by HermanMartinus** [comment]
👍 done
