### ISSUE TITLE
"go" word inside code block activates syntax highlighting

### ISSUE THREAD

**Issue by reueljonathan** [HermanMartinus/bearblog#255]
Hi!

I was writing a post, and at a specific part I tried to use a code block to show the file tree of a project using golang. Turns out that if the content in the block contains the word "go", it tries to infer the syntax as tsql and enables the syntax highlight.

![image](https://github.com/HermanMartinus/bearblog/assets/5330192/fe1c73dc-285b-4826-b644-114c7a15d068)

**Comment by YannickFricke** [comment]
@reueljonathan 

Heya!

You can always set the syntax to something different like so:

> \`\`\`my-new-syntax

So the file listing could be written as such:

> \`\`\`text
  ... listing comes here
  \`\`\`

So it would become the following:
![image](https://github.com/HermanMartinus/bearblog/assets/591450/5271ee70-ab17-41f8-b096-db588a362170)

Cheers!

**Comment by HermanMartinus** [comment]
Thanks @YannickFricke for responding. That's exactly how this is resolved. 

@reueljonathan here is a list of the languages supported by the code renderer: https://pygments.org/languages/
