### ISSUE TITLE
how to display 'posts' on a 'page'?

### ISSUE THREAD

**Issue by sanjai0py** [HermanMartinus/bearblog#257]
i created a "page"
![image](https://github.com/HermanMartinus/bearblog/assets/84461672/39c2d84e-b303-4e33-9e97-3fa9df7fed33)

and manually linking the posts
![image](https://github.com/HermanMartinus/bearblog/assets/84461672/a16e8174-55bd-43ef-b5a6-7005322e6f0d)

is there any way to show my blog posts like these without manually adding links?
![image](https://github.com/HermanMartinus/bearblog/assets/84461672/7c4579b2-7a76-4250-b817-31d73c412c9d)

**Comment by HermanMartinus** [comment]
This is a planned feature. I'll try get it out over the next week or so. In the meantime manually building the page is the only option, or using the Blog page. 

Feature card: https://bear.nolt.io/33
