### ISSUE TITLE
scrollbar moves layout a bit

### ISSUE THREAD

**Issue by cemreefe** [HermanMartinus/bearblog#26]
When I go from a page that doesn't overflow the page vertically to one that does, the appearence of the scrollbar shifts everything on the page a bit to the left.

You might want to take a look at [this stackoverflow discussion](https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page).

**Comment by HermanMartinus** [comment]
@cemreefe what browser/OS are you using? I can't seem to recreate this.

**Comment by HermanMartinus** [comment]
Closed due to inactivity
