### ISSUE TITLE
Red box artifact in code block

### ISSUE THREAD

**Issue by okomarov** [HermanMartinus/bearblog#260]
From the post: https://koma.bearblog.dev/how-to-tame-your-graphql-schema/

<img width="460" alt="image" src="https://github.com/HermanMartinus/bearblog/assets/3731173/d0411911-19d5-4127-8ab5-2a3dc6f1aeed">

It happens on the last code snippet, and remains even if I remove the `...`. You can compare with the previous code snippet where the boxes don't appear.

**Comment by HermanMartinus** [comment]
@okomarov These are syntax errors in the syntax highlighter for the specified language. Considering this is GraphQL you should be able to specify the highlighter using the format
```
```graphql
<code here>
```

Please let me know if this resolves it.

**Comment by okomarov** [comment]
I was using:

 ```gql
 
which appears to be working (the type is in green). I since moved content around and the boxes don't appear anymore.
