### ISSUE TITLE
on monetizing (advertising) bearblog.dev blogs

### ISSUE THREAD

**Issue by ghost** [HermanMartinus/bearblog#261]
As a casual blogger, to me it's unclear if running ad networks possible. I plan on using ethicalads.io, if I manage to build an audience.

There doesn't seem to be any mention in [the documentation](https://docs.bearblog.dev/), neither on:

https://docs.bearblog.dev/privacy-policy/  
https://docs.bearblog.dev/terms-of-service

You also don't explicitly mention **if commercial use is allowed**.

 bearblog of course will not sell any advertising, third-parties have to be used (e.g. ethicalads.io).

**Comment by 07416** [comment]
The question appears to  in fact be answered on this page:

https://docs.bearblog.dev/contributions/

> # Features available to contributors

> * In-content JS

This inquiry remains:

> You don't explicitly mention if commercial use is allowed.

**Comment by HermanMartinus** [comment]
Sorry for missing this issue. You're allowed to run ads on your blog so long as you're using your blog as a blog and not an explicit backlink site  :)
