### ISSUE TITLE
Localisation leaks on accounts/login

### ISSUE THREAD

**Issue by Summertime** [HermanMartinus/bearblog#264]
* https://bearblog.dev/accounts/login/

Refreshing every so often leads to the `Password` label being localized differently, I would assume adding `Accept-Language` to the `Vary` header would help. Not sure the cause however

**Comment by HermanMartinus** [comment]
Whoops. That's on me. I added localisation to the new custom filters and it looks like that leaks site-wide. Pushing a fix today.

**Comment by HermanMartinus** [comment]
Fixed in da95468f8c7dd3643d3759d9b63f5204b2c49baf
