### ISSUE TITLE
Error editing blog post

### ISSUE THREAD

**Issue by Niyes** [HermanMartinus/bearblog#265]
When trying to edit a post from the blog, the dashboard leads to a page at _"/dashboard/posts/link/"_ instead the uuid _"/dashboard/posts/kPuFagyusIJnaoTjSejs/"_ and displays as a blank page.

**Comment by HermanMartinus** [comment]
My guess is that the posts page hasn't been refreshed since the last update. Can you try reloading the post list page and see that the links update?

**Comment by Niyes** [comment]
After reloading, things are still the same.

**Comment by HermanMartinus** [comment]
Can you drop a link to your blog here or send it to me via email and I'll take a look and see if something went awry with the migration of your posts to the uid system

**Comment by Niyes** [comment]
https://niyes.bearblog.dev

**Comment by HermanMartinus** [comment]
Ah, I've found the issue and patched it. Thanks for bringing it to my attention 🙏
