### ISSUE TITLE
List of "blog posts" includes "pages"

### ISSUE THREAD

**Issue by dajare** [HermanMartinus/bearblog#267]
The codes for including ["latest blog post" lists][1] are terrific.

I have noticed, though, that `{{ posts }}` does not respect/filter-out any posts that have `is_page` set to **true**. 

My understanding of [the docs][2] suggests this behaviour is unexpected. It looks more like "bug" than "feature"! :)

Hopefully it's a quick fix. Thanks!

[1]: https://docs.bearblog.dev/embedding-blog-post-lists/
[2]: https://docs.bearblog.dev/post/#is-page

**Comment by HermanMartinus** [comment]
Good catch! I've just pushed a fix. It was an easy filter `is_page=False` :)
