### ISSUE TITLE
option to not show post in blog posts

### ISSUE THREAD

**Issue by cemreefe** [HermanMartinus/bearblog#27]
i like that we have the option to publish a post as either a page or a blog post, but I'd love to have an option to post it as neither so that the post is only reachable through its link.

for example I'll have a page called "error logs", and publish posts that are error logs and I don't want there pages showing up in my blog tab.

Sorry if there's already a way to do it but I couldn't figure out.

**Comment by HermanMartinus** [comment]
I understand your use case. The current feature that you could use in this respect is to have `Publish` unchecked and just use the preview link eg: `herman.bearblog.dev/error-logs?preview=true`.

I'll see if I can add a better feature for this in the future

**Comment by cemreefe** [comment]
> The current feature that you could use in this respect is to have `Publish` unchecked and just use the preview link eg: `herman.bearblog.dev/error-logs?preview=true`.

I'll try that then, thanks
