### ISSUE TITLE
Dark mode turn off

### ISSUE THREAD

**Issue by jsiddharth24** [HermanMartinus/bearblog#270]
Hey Herman,

Love the simplicity of the blog. A few questions from my side.  

1. How can we turn the dark mode off using CSS? 
2. How can you hide the dates?
3. How can you change the font for the landing page title

**Comment by HermanMartinus** [comment]
Glad you love the project :) 

These are all done in Themes in the CSS editor. You can remove the entire `@media` query with `prefers-color-scheme-dark` to remove dark mode for everyone, regardless of what their system settings are. 

You can hide the dates by setting 
```
time {
    display: none;
}
```

And you can also set the font in the CSS editor by modifying the main and secondary font in the `:root` section at the top of the CSS.
