### ISSUE TITLE
[Tiny Change] Please add this for EasyMDE widget for easy editing toolbar and to prettify Markdown? This is how:

### ISSUE THREAD

**Issue by salemandreus** [HermanMartinus/bearblog#274]
It's just these 3 lines to add [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) to a django project, (I added it in a django site [here](https://github.com/salemandreus/ideation-website/commit/8531de2b2ab106f283a50804ae7a9eec7a930ae1)) and it's really this simple:

#### Add to template:

Import EasyMDE:

    
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>

Enable for Element:

    
    <script>new EasyMDE({element: document.getElementById('id_content')});</script>

That's it!

**Comment by HermanMartinus** [comment]
So I certainly can't do that without pissing off a large chunk of Bear's user-base who value the simplicity of a simple text area (I also personally lean that way and dislike the vast majority of these editor interfaces). 

That being said, your feature request inspired me to add the ability to add your own footer content to your dashboard editors.

In `Settings / Advanced settings` you'll see a `Custom dashboard footer content` field. In there you can paste 

```
<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script>new EasyMDE({element: document.getElementById('body_content')});</script>
```

and your editors should work :)

**Comment by salemandreus** [comment]
Heya

I bought the premium subscription to test if that worked. 

I'm not able to make it work that way. It seems to be because the headers and footers apply to the public blog site, whereas the editing posts layout is separate(I tested that it didn't come through by adding text as the footer, which only shows in public view and not when editing a post or the ).

Would you be able to add it in, and if some people prefer the textarea, just set it as a toggle or have it as a configurable attribute or something? Surely being able to preview markdown live (even having it be optional) would be appreciated?

I'm currently having to navigate through to the next page every time to check that the markdown renders as I expected, and then back again to correct anything, and then forward again to check that _that_ edit rendered as expected, etc... which makes editing a really cumbersome process.

Thanks

**Comment by salemandreus** [comment]
Oh, Murphy's law, despite struggling with this for days,  immediately after writing all this, I discover that dashboard footer is a separate thing to the custom headers and footers! 

:face_palm: Please forgive me! 😅

And thanks for adding it, it looks great now!
