### ISSUE TITLE
Feature Request for Markdown Spoiler Tags/Content Obscurers for CWs

### ISSUE THREAD

**Issue by salemandreus** [HermanMartinus/bearblog#278]
Do you think you could add tags that allow people to obscure either topics people are sensitive to (triggers, phobias etc) or potential spoilers/other content people may wish to have hidden? 🙏

Like the spoiler tags one can add on Steam and Discord.

**Comment by HermanMartinus** [comment]
Thanks for suggesting this. There is currently a feature request here for that. You can vote on it and leave a comment if you'd like:

https://bear.nolt.io/174
