### ISSUE TITLE
Timestamp on Discovery News Feed - Newest

### ISSUE THREAD

**Issue by ChrisMartinus** [HermanMartinus/bearblog#28]
The timestamps on the newest discovery feed seem to be off. When I post an entry and view it on the feed, it says it was posted 17 hours, 45 minutes ago when it was actually posted moments ago.

**Comment by HermanMartinus** [comment]
I just noticed this too. If you leave the field blank, it sets it to the current day/time, but if you select "today" in the time field, it selects today at midnight, so you probably posted at 5pm UTC. If you have a suggestion on how to handle this. I'm thinking of just putting in some help text saying "leave blank to post 'now'".

**Comment by ChrisMartinus** [comment]
On my devices I only get the option to enter a date, not a full datetime. 

I understand it was a user request to have the option to modify the date, but since your ranking algorithm probably is impacted by these timestamps it might be worthwhile removing the feature - or have a *real date time field hidden that your feed uses.

**Comment by HermanMartinus** [comment]
Hmmm, that's not a bad idea. A "created_date" (hidden + used for the feed) and a "published_date" (used for organizing the user's `/posts` page)

**Comment by HermanMartinus** [comment]
This has been resolved by making the date optional which prepopulates it with the current date/time 073d38f5190babcf9f2f0a1a3af970b22b1da5fa

If a date is set it sets it for midnight. 
This isn't perfect, but the ranking algorithm is soon removing the use of time.

**Comment by dajare** [comment]
Aha!! Okay - I think now I understand. **Proposal**: add this info to [the documentation][1]!

I have been specifying my published date as `yyyy-mm-dd` when I save a new post. **That is a bad idea**, at least as far as *real* post timestamp is concerned, and it's place in the "Discovery" fee.

I just [made a post][2] and (as you do) checked the discovery feed ... and it wasn't on page 1, but it was `#23` on page 2, seemingly posted "11h 55m ago". What?!

But of course: I put the 2024-01-04 date in my post header, and saved a draft at 11:55 UTC (I live in the UK). NOW I understand why that happened. If I had left the `published_date` blank, I assume it would have been fine. (I.e., I would have shown up at the expected place on the discovery fee.

Perhaps [the docs][1] could spell this out? My suggestion:

> \[... The date at which the article is to be published. This can be left blank to post *now* or be set using the following standard: `YYYY-MM-DD`. \] If you set the date manually, the post *time* will be set to midnight UTC. To get the precise timestamp at the moment of posting (or saving a draft), leave this field blank.

Just a thought! At least now *I* know. :)   
**P.s.** And I just re-saved that post with `published_date` specified as `2024-01-04 11:55`, and it's moved to `#1` in the "Most recent" feed. :)

[1]: https://docs.bearblog.dev/post/#published-date
[2]: https://gmal.bearblog.dev/from-patterns-to-notes

**Comment by HermanMartinus** [comment]
Thanks for brining this up. By and large I just expect people to just press publish if they are publishing on that day and adding the date manually does default to midnight UTC unless time is specified. 

I'll try make this more clear in the docs :)

**Comment by dajare** [comment]
Thanks for the reply! I'm really enjoying BearBlog - what blogging *should* be like. :100:
