### ISSUE TITLE
Home "bear face" button overloads the line when eyes open

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#280]
He is cute with his eyes closed, but with eyes wide open he loses one ear and pushes the whole line to the bottom:
![image](https://github.com/HermanMartinus/bearblog/assets/80604512/cc8b42e7-e52f-4d40-bcbf-a663f524d50e)
![image](https://github.com/HermanMartinus/bearblog/assets/80604512/9f7c04ba-3dda-4972-b974-858952f65faf)

Using Firefox 125.0.2 on Mint

**Comment by HermanMartinus** [comment]
Ah interesting. That seems to be due to the default font on Firefox (I can't seem to recreate it thought). I've added an extra 2px to buffer it a bit. Please let me know if that solves it for you and if so, you can close the issue.

**Comment by HermanMartinus** [comment]
@Cwpute are you using a different font on the dashboard?

**Comment by Cwpute** [comment]
Not at all… i looked into Advanced Settings and i didn't even see an option for personalized styling. Weird !
Is it exclésive to subscribers ?

Le 30 mai 2024 08:52:34 GMT+02:00, Herman ***@***.***> a écrit :

**Comment by HermanMartinus** [comment]
It should be working fine now. It turns out by setting `white-space: nowrap` I don't even need to handle the width. @Cwpute if this works for you please close the issue :)

**Comment by Cwpute** [comment]
I can confirm it works !
