### ISSUE TITLE
Issue with Uploading Non-HDR AVIF Files on Bearblog

### ISSUE THREAD

**Issue by Shikibashi** [HermanMartinus/bearblog#282]
I’ve learned about the AVIF format, which is emerging as a superior choice for photographs due to its HDR support. While I’m aware that HDR’s mainstream adoption is still a distant prospect, and I don’t expect Bearblog to support it just yet, I’ve optimized my workflow by exporting images from Photoshop in AVIF format to benefit from the space savings. Achieving comparable visual quality at 2MB, I would love to utilize AVIF to expedite the loading times of my photography page on Bearblog, enhancing the user experience.

However, when I attempt to upload non-HDR AVIF files, the process appears to initiate but fails to provide a download link. This issue might be prematurely attributed to a DigitalOcean problem, although the exact cause is unclear. Uploading JPEG or PNG files works seamlessly, but uploading non-HDR AVIF files results in no action

**Comment by HermanMartinus** [comment]
I've just pushed an update supporting .avif files :)
