### ISSUE TITLE
Invalid slug with an underscore generates 400 server error on view

### ISSUE THREAD

**Issue by gitstua** [HermanMartinus/bearblog#287]
👋 Hi Herman, great work on the blogging platform!

I just created a username of `cloudy_stuey` and created some basic content. Each time I visited the site I saw
![Image](https://github.com/HermanMartinus/bearblog/assets/25424433/ea53fb90-d6bb-4f4c-9440-b01c6411d6d2)

I see #47 mentioned this area too however is closed.

To reproduce the problem
1. sign up for new account
2. create blog with `_`
3. press `view` on the dashboard

**Comment by HermanMartinus** [comment]
Thanks for reporting this. Underscores should not be used in slugs or subdomains at all. I do enforce that on slugs, but not on subdomains. I'll set that up shortly.

**Comment by HermanMartinus** [comment]
Fixed in the latest commit. Thanks again.
