### ISSUE TITLE
2 bugs (?) related to robots.txt extra content

### ISSUE THREAD

**Issue by gwerbin** [HermanMartinus/bearblog#290]
Bearblog is great! I found 2 possible bugs related to setting extra robots.txt content on the `dashboard/settings/advanced` page:

1. Pressing "enter" in the text box has no effect. I can paste newlines in just fine, but for some reason my enter key doesn't work when trying to type into that box manually.
2. The robots.txt file with my appended content appears on my _custom_ domain at https://journal.gregory.werbin.net/robots.txt, but only the default content is present on my Bearblog domain at https://hexology.bearblog.dev/robots.txt. I checked with Curl, so it doesn't seem like a browser caching problem.

**Comment by HermanMartinus** [comment]
@gwerbin I've patched the pressing Enter problem. I introduced that accidentally in an update that was to prevent the "back" button from getting triggered on Enter.

As for the robots.txt content, I suspect that it was getting cached *somewhere*. It's identical now :) 

![Screenshot 2024-06-17 at 08 41 34](https://github.com/HermanMartinus/bearblog/assets/26326265/78d373a9-20eb-4d14-bf40-f71924b79caf)

**Comment by gwerbin** [comment]
Thanks a lot!
