### ISSUE TITLE
underbrace renders naively

### ISSUE THREAD

**Issue by OfekShochat** [HermanMartinus/bearblog#291]
```
\underbrace{G + \ldots + G}_{\text{n times}}
```

renders as (on mobile; on my machine it doesn't recognize the character):
![Screenshot_20240617-134540](https://github.com/HermanMartinus/bearblog/assets/50481015/6a268043-b0c1-4aa3-b9dc-0a4a7ecc7676)

**Comment by OfekShochat** [comment]
posted it here because this was fixed in [this commit](https://github.com/roniemartinez/latex2mathml/issues/302) which was committed after 3.64.0 was released.

**Comment by HermanMartinus** [comment]
I've just bumped the version up to 3.77.0

Give it a spin and close the issue if everything looks good to you :)

**Comment by OfekShochat** [comment]
Works! Thanks
