### ISSUE TITLE
Ho to add a react program on my blog

### ISSUE THREAD

**Issue by gogainda** [HermanMartinus/bearblog#294]
What is the best option to share the React app on the blog page? Iframe or is there a better option available? (Framework is not important, if needed I can convert it to any JS one)

**Comment by HermanMartinus** [comment]
Is this a code demo, or are you trying to build a react site on top of Bear? 

For a code demo you can include it using something like CodeSandbox or Replit. However, if you're trying to build a React Bear Blog, then your guess is as good as mine :)

**Comment by gogainda** [comment]
code demo, in particular, the artifact generated by Claude AI

**Comment by gogainda** [comment]
I was
