### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by wmorrel** [HermanMartinus/bearblog#3]
Hey, awesome project! Have you considered adding some basic stats on page views for individual posts and such? I love the idea of not tracking folks, but some basic low-level stats would be awesome just to be able to tell which posts are popular.

**Comment by HermanMartinus** [comment]
Yeah! I've got it on my list of things to do. First step, get SSL working on custom domains, step 2 RSS, step 3, basic stats :)

**Comment by HermanMartinus** [comment]
I have some basic stats working. Pop me an email with your blog subdomain to be added to the analtics beta.

**Comment by HermanMartinus** [comment]
Stats are working and available in the Analytics tab on the dashboard

**Comment by Yolakalemowa** [comment]
> Stats are working and available in the Analytics tab on the dashboard

Hi... Do stats only show for **discoverable** posts?

**Comment by HermanMartinus** [comment]
No, stats are collected and shown for all posts regardless of whether they show up on the Discovery feed.
