### ISSUE TITLE
custom meta elements

### ISSUE THREAD

**Issue by 3052** [HermanMartinus/bearblog#301]
I need to add a meta element like this:

~~~html
<meta name="go-import" content="hello world">
~~~

but it seems I cannot currently do that

**Comment by HermanMartinus** [comment]
Hmmmm, my guess is that the validator is expecting a `property` value. Try adding an empty one (`property=''`) and let me know if that works.

**Comment by HermanMartinus** [comment]
Hmmmm, I can't recreate the issue you're having. When I use the provided meta tag it adds it to head no problem. 

Could you send me a link to your site (via email or here is fine). 

![Screenshot 2024-10-08 at 14 27 40](https://github.com/user-attachments/assets/dd74e88b-4137-4976-9fb6-16b7a44345c9)

**Comment by 3052** [comment]
maybe I just am not doing what you are doing - can you give the steps you took to produce that output?

**Comment by 3052** [comment]
it seems that might be a paid option

> Add code to head and footer elements

https://bearblog.dev/dashboard/upgrade

I am currently using NeoCities, I guess I will just stick with that

**Comment by HermanMartinus** [comment]
The functionality I'm using is available on free blogs. It's in Settings/Advanced settings called `Custom meta tag`. It seem to be working perfectly fine :)
