### ISSUE TITLE
Bearblog inaccessible with QuiteRSS

### ISSUE THREAD

**Issue by Nekkowe** [HermanMartinus/bearblog#304]
Hello!

I can add Bearblog RSS feeds just fine in e.g. Thunderbird and through the browser, but when trying to add the feed to QuiteRSS, I get the following error message from the server:

![image](https://github.com/user-attachments/assets/96317886-4d7e-4421-82f3-4289ab60743f)

Is the user agent string blocked or something?

**Comment by Nekkowe** [comment]
Oh, I'm running into the same problem with RSS Guard.

**Comment by HermanMartinus** [comment]
Sorry about that. I've been trying to get Cloudflare to play nicely in blocking bots from scraping blog content for AI applications like model training. But it seems that their verified bots list isn't going to cut it. My guess is that it's only the better known RSS readers that have been approved. 

I've turned it off and taken some other precautionary measures to prevent blogs being scraped for LLM training. 

Can you let me know if your RSS readers are syncing the content correctly now?

**Comment by Nekkowe** [comment]
Yup, both of them work fine now! Thank you very much for the quick response! :>
