### ISSUE TITLE
Embedding blog post lists only allows one tag filter

### ISSUE THREAD

**Issue by pedrokkrause** [HermanMartinus/bearblog#307]
It seems it is not possible to use more than one tag filter to embed blog post lists. Having more than one tag filter would allow filtering by a topic and language, for example.

**Comment by HermanMartinus** [comment]
This is on my list of things-to-do 👍

**Comment by HermanMartinus** [comment]
This is now available with the following format:

```
{{ posts|tag:writing,opinion }}
```
