### ISSUE TITLE
Language filtered RSS

### ISSUE THREAD

**Issue by IkelAtomig** [HermanMartinus/bearblog#308]
While following [Discover](https://bearblog.dev/discover/?newest=true) feed there are a lot of languages supported. It would be better follow RSS feed based on languages as the sorting mechanism given in page.

Such as https://bearblog.dev/discover/feed/?type=rss&newest=True&lang=en

**Comment by HermanMartinus** [comment]
I've just added a language filter to the RSS feed in 8c6632d7f75c4d155e4a64460135ec5957c0afdd
