### ISSUE TITLE
CSS textarea isn't fully  accessible to screen readers.

### ISSUE THREAD

**Issue by rkingett** [HermanMartinus/bearblog#309]
After upgrading to any of the paid tears, the CSS multiline edit field that allows users to edit the CSS of a given theme isn't fully accessible to screen reader users.

After updating to a paid tear, when trying to edit the text within the CSS edit field, currently found under the themes page within a users dashboard, even though there is CSS in there, when navigating with a screen reader, NVDA on Windows, and VoiceOver on Macs, that editbox appears empty and it appears to not contain any code or electronic text.

A screen reader user would have to know to select all text, then pase the text elsewhere in order to edit it.

No matter the navigation method, that text area appears empty until a user selects all then copies and pastes the text elsewhere.

If that is what a user is supposed to do after all, then I'd like some text explaining as such before the textarea.

If a user pastes in CSS from elsewhere, there is no way to review the text afterward. The textarea still appears blank and the text inside isn't showing to screen reader users at all.

**Comment by HermanMartinus** [comment]
@rkingett I've just added an option on the Theme page beneath the CSS called `Enable Codemirror`. If this is disabled it will turn the CSS editor into a normal textarea which should work perfectly with screenreaders. Please give it a spin and if it works well close this issue :)

**Comment by rkingett** [comment]
Unfortunately this did not work for me and I tried refreshing the page after disabling the checkbox! Perhaps if you could tell me why it has code mirroring by default I could probably better give ideas of what we can do? I tried to see if there was any change between the toggled states but there appeared to be none!

**Comment by HermanMartinus** [comment]
Try disabling the checkbox and clicking Save. Bear operates all of its forms synchronously.

**Comment by rkingett** [comment]
It works! My only other change would be to move the code mirroring checkbox above the edit box so the publish button is near that checkbox since there's technically no "save" button!
