### ISSUE TITLE
RSS feed doesn't include tags

### ISSUE THREAD

**Issue by vexillia** [HermanMartinus/bearblog#310]
As the title says the atom feed doesn't include the post tags.  These can be important when the post is posted to social media.  

Can they be included please?

**Comment by HermanMartinus** [comment]
Completed in 2e8b81f32944b8c15c0d8d6e9c93fa2588a1261b

Let me know if you run into any issues :)

**Comment by vexillia** [comment]
Excellent.  Thank you.
