### ISSUE TITLE
URL Hierarchy Support

### ISSUE THREAD

**Issue by joeyagreco** [HermanMartinus/bearblog#312]
1. Set up [Nav](https://bearblog.dev/{username}/dashboard/nav/) like so `[Home](/) [Blog](/blog/)`
2. Create a [post](https://bearblog.dev/{username}/dashboard/posts/)
3. Set the post `link` to `foo`
4. The post is now accessible at `https://subdomain.bearblog.dev/foo`
5. Set the post `link` to `blog/foo`
 - On `publish`, the forward slash (`/`) is removed

Ideally, there would be a way to have the path of the `foo` post set too `blog/foo` instead of `/foo` 

It seems there is not a way to have a post live in a nested path.

**Comment by rkingett** [comment]
I think this would be a good thing for the discussion board. For what I understand, GitHub is used for  logging issues/ bugs.   @HermanMartinus  If this is possible currently, the documentation does not talk about this at all yet.

**Comment by HermanMartinus** [comment]
@joeyagreco Bear's path structure explicitly uses `https://example.bearblog.dev/foo` and doesn't support additional paths with forward slashes, eg: `https://example.bearblog.dev/blog/foo`

However, you can set that using the `alias` attribute, in your case `alias: /blog/foo` which would make the post available at `https://example.bearblog.dev/blog/foo` but redirects to the blog's link `https://example.bearblog.dev/foo`

**Comment by joeyagreco** [comment]
> I think this would be a good thing for the discussion board. For what I understand, GitHub is used for logging issues/ bugs. @HermanMartinus If this is possible currently, the documentation does not talk about this at all yet.

Do you have a link to the discussion board?

There doesn't seem to be a discussion tab enabled for this repo, and the Wiki tab just links to the docs.

**Comment by rkingett** [comment]
Yeah, find it at https://bear.nolt.io/
