### ISSUE TITLE
suggestion: water.css

### ISSUE THREAD

**Issue by diomed** [HermanMartinus/bearblog#33]
Hi

I think that integrating this project could help make pages look more nicer. 
Especially sign up page

https://github.com/kognise/water.css

**Comment by josevazquz** [comment]
such a great idea! 
[dark](https://i.imgur.com/PhpnTuA.png)
[light ](https://i.imgur.com/HphzdUs.png)

**Comment by HermanMartinus** [comment]
You can now add an external stylesheet (like water) to your Bear blog in the styling tab in the dashboard
