### ISSUE TITLE
Suggestion: Canonicals

### ISSUE THREAD

**Issue by rjpdev** [HermanMartinus/bearblog#34]
Let us add canonical URLs to our posts to link back to our sites. Maybe add a link to the posts, "view original", or something like that for these cases.

**Comment by HermanMartinus** [comment]
Good idea. I'll add it to the list.

**Comment by HermanMartinus** [comment]
I've added canonical url support for posts bce6bd7e7bf700447e7a736086543ff1c1a779ce
When adding a canonical url to a post it appends a `View original` anchor as suggested.
