### ISSUE TITLE
Feed problems: permalink and date

### ISSUE THREAD

**Issue by manton** [HermanMartinus/bearblog#35]
I noticed when someone tried to use Bear with Micro.blog that Bear's feed has a few problems:

* The `id` should be a URL.
* The `link` is also not a valid URL (missing "http"), and it's pointing to /feed instead of the actual permalink for the blog post.
* The `updated` date keeps changing when a feed is requested. It doesn't look like it's actually the date/time that the blog post was published.
* The feeds also don't validate in: https://www.feedvalidator.org

Happy to help if you have any questions or need someone else to test.

**Comment by HermanMartinus** [comment]
@manton Thanks for this, I'll address these issues in a day or two and would appreciate you taking a look over it once I'm done.

**Comment by HermanMartinus** [comment]
I've resolved the issues. I've also added RSS as a feed type, and will make a note to add JSON support at a later date. Please let me know if you manage to use this with Micro.blog. If everything works you can close the issue. 

## Atom
http://herman.bearblog.dev/feed/
[Validator results](https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fherman.bearblog.dev%2Ffeed%2F)

## RSS
http://herman.bearblog.dev/feed/?type=rss
[Validator results](https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fherman.bearblog.dev%2Ffeed%2F%3Ftype%3Drss)

**Comment by manton** [comment]
Great, thanks @HermanMartinus! This is much better. One last thing: While the `guid` (RSS) and `id` (Atom) is correct now, I think the `link` tag is still pointing to the feed URL instead of the permalink of the entry. If you can change that too, I think it will be perfect.

Glad to hear you're considering JSON Feed for later too!

**Comment by HermanMartinus** [comment]
Ah right. It is. I was looking at the root link here:
```
<link href="http://herman.bearblog.dev/" rel="alternate"/>
<link href="http://herman.bearblog.dev/feed/" rel="self"/>
```
 
Pushing a fix now.

**Comment by HermanMartinus** [comment]
```
<entry>
    <id>http://herman.bearblog.dev/hello-world/</id>
    <title>Hello World!</title>
    <updated>2019-09-16T16:03:08+00:00</updated>
    <author>
      <name>herman</name>
      <email>hfbmartinus@gmail.com</email>
    </author>
    <content>Content...</content>
    <link href="http://herman.bearblog.dev/hello-world/" rel="alternate"/>
  </entry>
```

Much better :)

**Comment by KhoomeiK** [comment]
Is it possible to serve the feed as HTML, such that a user can scroll through all my posts reverse chronologically with the only the first N characters of each post showing? Or does it only support RSS right now?

**Comment by HermanMartinus** [comment]
@KhoomeiK currently it `/blog/` shows all your posts reverse-chronologically. It doesn't show the description of the post, only the title though. Eg: https://herman.bearblog.dev/blog/

**Comment by KhoomeiK** [comment]
Yup that's fine, but I think having a small "preview" of each blogpost is pretty valuable and a feature that many other blogging platforms have. If you think it makes sense, I can start working on a pull request.
