### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by chrislessard** [HermanMartinus/bearblog#36]
I noticed that Latex support is currently under consideration in the roadmap. 

I wondered if this would involve incorporating a third-party library like [KaTex](https://katex.org/) if it fits the speed threshold. Maybe it could be something the user enables or not to determine if it should even be loaded. 

WDYT ? I'd be to help out with it :)

**Comment by HermanMartinus** [comment]
Woah, thanks Chris. I was considering using MathJax but my initial tests with it were underwhelming. I'll give KaTeX a spin.

**Comment by chrislessard** [comment]
Let me know if I can lend you a hand!

**Comment by nitronoid** [comment]
+1 for this, it would be a great feature for some math blogging :)

**Comment by HermanMartinus** [comment]
It's in the works. In the meantime, using https://upmath.me/ then selecting `md` as the output works great.

**Comment by dominiwe** [comment]
Is this still being worked on? I think server side rendered katex would be best and doable.

**Comment by HermanMartinus** [comment]
@dominiwe it's on the sidelines at the moment but is something I do want to get working. I'm currently looking at [Markdown Katex](https://github.com/mbarkhau/markdown-katex) but at the moment it breaks a lot of existing rendering. It'll get some focus in future development.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
