### ISSUE TITLE
Image guidance

### ISSUE THREAD

**Issue by wachunga** [HermanMartinus/bearblog#37]
This is a fairly common use case: I have an image locally and want to include it in my blog post.

Do you have any plans to support that? eg uploading to S3. Or at least offer some guidance in the editor?

Great project!

**Comment by HermanMartinus** [comment]
Hey, sorry for the late reply. Bear doesn't have any S3 storage hooked up, but what you can do is upload the image to imgur and add it in markdown like this:
```
![Alt text](https://imgur.com/link-url)
```

**Comment by wachunga** [comment]
Thanks. I think some guidance in editor could be helpful, but at least a search will find this. Re-open if you like :)

**Comment by 07416** [comment]
> Bear doesn't have any S3 storage hooked up, but what you can do is upload the image to imgur and add it in markdown like this:
> 
> ```
> ![Alt text](https://imgur.com/link-url)
> ```

This is against [Imgur's terms of service](https://imgur.com/tos):

> don't use Imgur to host image libraries you link to from elsewhere, content for your website

You're also suggesting using Imgur at least on the following pages (an ad-supported social media platform doesn't pair well with bearblog either):

https://docs.bearblog.dev/home-page/  
https://docs.bearblog.dev/post/

Imgur may also block the bearblog.dev domain from hotlinking, if they haven't already. Hosting images off-site may negatively affect SEO. [Imgur's privacy policy ](https://imgur.com/privacy) may not appeal to the bearblog users.

**Comment by HermanMartinus** [comment]
Image hosting by Bear is available if you upgrade (unfortunately it's not something I can offer to free accounts). There are alternatives to Imgur such as ImgBB. I even believe you can do it from Google Photos if you select the photo to be public.

**Comment by 07416** [comment]
@HermanMartinus Can you at least host the images used for internal documentation? For instance you are hotlinking the blog style screenshots from Imgur (on `https://bearblog.dev/dashboard/styles/`).

I would avoid associating bearblog with any proprietary, ad-supported image hosts. May give a negative first impression to many.

---

I'm not asking any image hosting for free accounts, of course the feature is only part of the paid plan.
