### ISSUE TITLE
suggestion: favicon

### ISSUE THREAD

**Issue by carlsmedstad** [HermanMartinus/bearblog#38]
Having a favicon, possibly a minimized version of the bear, would neat IMO. It makes bookmarks more distinguishable and browser tabs more uniform.

By the way, great idea and execution!

**Comment by HermanMartinus** [comment]
Thanks for the suggestion. I'll add it to the next update :)

**Comment by HermanMartinus** [comment]
Even better, added an emoji element as part of an embedded svg's text. This could easily be set up so people can choose their own favicons from the standard emoji list. 
`<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐼</text></svg>">`
