### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by krthr** [HermanMartinus/bearblog#4]
Hi! I really love this project. Thank you for making this.

I just wanted to say it would be nice to have tags o categories

**Comment by HermanMartinus** [comment]
I'll made to to add them :) Thanks for the suggestion

**Comment by HermanMartinus** [comment]
I've added the ability to add hashtags to categorize posts **(Note: the hashtag list needs to be preceded by a backslash so it's not parsed as markdown)**

eg:
```
Post content
content content
content

\#bear #blog #essay
```

**Comment by HermanMartinus** [comment]
I still have to make it filterable on the /posts page

**Comment by HermanMartinus** [comment]
Tags are now filterable and are dynamically linked with hashtags. Check it out https://herman.bearblog.dev/markdown-test/
