### ISSUE TITLE
Suggestion: Table of Contents / Direct Links to Headings

### ISSUE THREAD

**Issue by makramkd** [HermanMartinus/bearblog#40]
Hey Herman! 

Loving bearblog so far. I was wondering if adding an optional table of contents has crossed your mind, especially for longer blog posts (I just wrote a fairly long one).

Another suggestion I have would be to make the headings in the blog linkable. I wonder if I can do that myself though, if I make the heading content itself a link, like:

```md
## [Hello World](#hello-world)
```

So that we can link readers directly to a section of the blog post.

EDIT: I'm not sure if you're accepting contributions yet, but adding a CONTRIB.MD or similar (contribution guidelines) for people like myself may be helpful just in case we can add some features in a fork.

**Comment by HermanMartinus** [comment]
Hey @makramkd, thanks for the kind words, and I'm glad you're finding it useful :) 

I have added TOCs to the [roadmap](https://github.com/HermanMartinus/bearblog/wiki/Roadmap). I am accepting contributions if you're familiar with Django. I plan to get to a bunch of these requests early next week.

**Comment by HermanMartinus** [comment]
Internal links are now available. Each heading gets an id (which is the heading content slugified). It can then be linked internally. Eg:
```
[Link to heading 4](#heading-4)

## Heading 1

## Heading 2

## Heading 3

## Heading 4
```

Let me know if you experince any issues with it.
