### ISSUE TITLE
Tags that aren't used by any posts don't get removed

### ISSUE THREAD

**Issue by adamzerner** [HermanMartinus/bearblog#42]
What I did:
- Start from scratch.
- Create a blog post with a #code tag.
- Delete that blog post.
- The code tag is still there.

Edit: Actually, after adding a second post the old #code tag went away. I'm not sure if there's an issue that's worth fixing or not here so I'll leave this up and let you decide.

**Comment by HermanMartinus** [comment]
Ah, thanks for pointing this out. The tags regenerate for the user on saving a post, but not on deleting a post. Will push a fix soon.
