### ISSUE TITLE
RSS feed autodiscovery

### ISSUE THREAD

**Issue by solderpunk** [HermanMartinus/bearblog#45]
Nice project!  Is there any chance you'd consider adding `<link rel="alternate" type="application/rss+xml">` tags to the `<head>` of Bearblogs, so feeds can be discovered programmatically?  As it is, they are effectively a secret/hidden feature - I actually initially assumed (to my great disappointment!) that there *were* no feeds because of the lack of a `<link>` for them.  I had to search through closed issues to find the `/feed` URL convention.

**Comment by HermanMartinus** [comment]
Solid point @solderpunk. I'll add the link to the `<head>` today

**Comment by HermanMartinus** [comment]
Resolved here 967b6349686ace8166ba042497a868e7feae2084
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fherman.bearblog.dev

**Comment by solderpunk** [comment]
Thanks for the speedy action!  Personally I would probably include it in the `posts.html` template as well, but that's up to you.

Very happy to see more and more people/projects trying to push the web in this direction.  Keep up the good fight!

**Comment by HermanMartinus** [comment]
@solderpunk Addressed in 6331082b8f4e56b0e832611093b3a41a56651f12 👍
