### ISSUE TITLE
Date picker traps screen reader.

### ISSUE THREAD

**Issue by rkingett** [HermanMartinus/bearblog#46]
This is exactly what I've been looking for nearly a year now. It is so brilliant, simple, and just everything.

There is one issue I had, running NVDA, the free and Open source screen reader.

The date picker traps the screen reader in that area. Would it be possible to make the months, a Combo box, and the day and year, a simple edit box?

Or you could have a radio button that says, post now or later? And if Later is selected, then the calendar options pop out.

Thank you for developing this. This is really great.

The name has 3 annoying bullets in it, but I can live with that. :)

**Comment by HermanMartinus** [comment]
Thanks for the kind words :) I hadn't tested a screen reader on it, but will put it on my list of things to do.

**Comment by rkingett** [comment]
It's actually perfect as is! Which is why the roadmap has me a bit concerend, with regards to the below.

> Code highlighting.

But if you keep things simple, native, code. HTML, text boxes, native HTML text areas, and basically, keeping things simple and native, it will remain fully accessible.

The only issue now is the date picker, but this can be worked around by making the Month and day and year a combo box, or, making the month a combo box, and the rest, input fields. Edit fields.

**Comment by HermanMartinus** [comment]
@rkingett I've taken code highlighting off the roadmap as my tinkering with it lead to me having to compromise the whole "no JS" ethos. I would also like to make the site as screen-reader friendly as possible :)

**Comment by yunruse** [comment]
@HermanMartinus Syntax highlighting can be done server-side! With a library like [pygments](https://pygments.org/), you could run code-highlighting whenever the post content is saved or rendered, whichever is more convenient.

**Comment by HermanMartinus** [comment]
Yeah, I fiddled around with pigments a bit and managed to get it semi-working. I'll probably give it a proper spin in the near future :)

**Comment by HermanMartinus** [comment]
Syntax highlighting has been implemented and tested with a screen reader and works well. 🎉
