### ISSUE TITLE
Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.

### ISSUE THREAD

**Issue by chancetudor** [HermanMartinus/bearblog#47]
My titles for a new blog post are being rejected with the error message: "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."

My titles are nothing out of the ordinary. They only contain letters, numbers, and hyphens. I've tried various lengths to no avail. Any hints as to what might solve this?

**Comment by HermanMartinus** [comment]
I've tested it my side and don't seem to have a problem with it. https://herman.bearblog.dev/testing-permalinks/?preview=true

Could you include a bit more info for me. Is it clientside or serverside validation that's failing? What's the name of your blog, maybe I can suss out the problem there.

**Comment by chancetudor** [comment]
I was trying to post using Brave Browser (v. 1.12.114) and was having the error but tried posting in Safari (v. 13.1.2) and it worked without any error. I'm not sure if it was clientside or serverside... probably clientside, seeing as switching browsers worked. My blog: modernmusic.bearblog.dev. 

Bear rocks man, thanks for making this!

**Comment by HermanMartinus** [comment]
Thanks :) 

I just did a test in Brave and it worked fine. This theoretically this shouldn't be happening as that error is thrown by Django on the slugfield (permalink) if there is an invalid slug. I'll poke at it a bit and see what I can find.
