### ISSUE TITLE
Any way to disable markdown for writing posts?

### ISSUE THREAD

**Issue by gulkily** [HermanMartinus/bearblog#49]
Is there any way to disable markdown and just write in plain text (or html)?

**Comment by rkingett** [comment]
I think you can do it either way, since it's a simple text editor area. Try HTML. I personally find Markdown lightyears easier to write than HTML. If you mean, Rich text, I don't think there is a way to write in rich text.

**Comment by HermanMartinus** [comment]
Thanks @rkingett, you're correct. You can write in plain text and in HTML as well as Markdown. There is no functionality for rich text.

**Comment by gulkily** [comment]
The reason I want to disable Markdown is that I write with a lot of in-text formatting which I want to remain as is.

**Comment by rkingett** [comment]
It actually sounds like you want the creator to enable CSS wrapping. Disabling markdown alone won't achieve the results you are looking for.

If I could make a suggestion, write.as has this CSS style enabled.

The editor works for writing in plain text, HTML, and Markdown. Just not rich text. If you want to write HTML and stylize it, I think you would need CSS properties for that.

But, at the moment, HTML and plain text works in the editor as is.

**Comment by gulkily** [comment]
All I'm looking for is that when I type something like: abc*123* or *abc123*, it is not converted to italics, but left just as I typed it.

**Comment by HermanMartinus** [comment]
@gulkily I see what you mean. Unfortunately for your use case you'll have to escape the characters reserved for markdown. There is currently no text-only version available.

**Comment by gulkily** [comment]
Thank you for your response. Unfortunately, this is a deal-breaker for me. I enjoyed using your project, thank you for putting it out there.

**Comment by HermanMartinus** [comment]
I understand. :)
