### ISSUE TITLE
!Important

### ISSUE THREAD

**Issue by krthr** [HermanMartinus/bearblog#5]
I think there is a bug. If a go to https://bearblog.dev/dashboard/posts/3/ I can see the content of the post and save it in my account. 

Access to the editor page of posts that aren't mine should be restricted.

**Comment by DivisionMax** [comment]
Adding onto this, generally, URLs should not include a guess-able primary key. Better to use a non-editable UUID, https://docs.djangoproject.com/en/3.0/ref/models/fields/#uuidfield

**Comment by HermanMartinus** [comment]
I'll take a look into this 🤔

**Comment by HermanMartinus** [comment]
Addressed [here](https://github.com/HermanMartinus/bearblog/commit/5e3d9496d2e1ebba8efcd3c415324ba2afc44322). Going to keep this open as I implement @DivisionMax suggestion.

**Comment by HermanMartinus** [comment]
This is actually fine for now.
