### ISSUE TITLE
Option to export posts 

### ISSUE THREAD

**Issue by vikramnr** [HermanMartinus/bearblog#52]
@HermanMartinus , It would nice to have option to export post in Markdown or text format as well

**Comment by HermanMartinus** [comment]
That sounds doable. What kind of deliniation would be useful to you in a markdown format? 
```
#  Title
*date*
...post content...
***
# Title
etc
```

**Comment by vikramnr** [comment]
I'm not sure about that, so whichever you think would be useful :+1:

**Comment by HermanMartinus** [comment]
This doesn't have a high priority for me at the moment. In the meantime you can use the RSS feed for your blog to export that information in XML format. Eg: https://herman.bearblog.dev/rss/

**Comment by minthemiddle** [comment]
Some raw dump of the posts would be a lot more valuable than formatted XML. Even a SQL dump would give a lot more confidence than processed data (as in the XML). I cannot reuse the XML easily in another markdown system and it creates a lock-in for any markdown writing process - unless I write locally first and just copy to Bearblog at the end (but this becomes tedious quickly).

The prefered markdown would be with YAML metadata (à la [Pandoc](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block):

```
---
title:  'This is the title: it contains a colon'
tags: [nothing, nothingness]
permalink: '#'
(+ all other fields)
...

# The post 

As raw markdown

```

**Comment by HermanMartinus** [comment]
Exporting can now be done in the admin panel of the dashboard
