### ISSUE TITLE
Boxes / Callouts

### ISSUE THREAD

**Issue by scrollyclic** [HermanMartinus/bearblog#54]
I like this feature of fastpages. It would be great to see this feature in BearBlog.

https://fastpages.fast.ai/fastpages/jupyter/2020/02/21/introducing-fastpages.html#Boxes-/-Callouts

**Comment by reustle** [comment]
Why I agree that these callouts are useful, I feel they’d strongly clash with the overall style and design of bearblog.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
