### ISSUE TITLE
User email visible in /feed

### ISSUE THREAD

**Issue by mudkipdev** [HermanMartinus/bearblog#55]
I just went on the /feed page of my blog, and saw my email there. Can we have an option for this to be anonymous? Or does that already exist?

**Comment by HermanMartinus** [comment]
Thanks for spotting this. I'm going to go ahead and make it anonymous by default.

**Comment by HermanMartinus** [comment]
Resolved in 77fb0f3bb969ca88b89c321344de032fbefe0164
