### ISSUE TITLE
favicon / emoji support limited

### ISSUE THREAD

**Issue by vanhecke** [HermanMartinus/bearblog#57]
Hi,

Currently the favicon inputbox has a maxlength="2".
But many emoji's have a length of 4.
The female shrug 🤷‍♀️ works while the male shrug 🤷‍♂️ does not. 

I gave up on understanding emojis and unicode some time ago.

**Comment by HermanMartinus** [comment]
Thanks for notifying me. I think there are very few people who understand unicode 😄 

I'll address this in the next update.

**Comment by HermanMartinus** [comment]
Resolved in 52b2aa315c77b1abdaa31c9793062ffc3a92385e
