### ISSUE TITLE
Request: Ability to disable Toasts

### ISSUE THREAD

**Issue by reustle** [HermanMartinus/bearblog#59]
In an attempt to resist the mass spread of “likes” across the internet, turning every piece of content into a popularity contest, I’d love to be able to remove the option to Toast on my blog posts. I like the feature, just prefer not to have it on my content. I understand you use this for the discovery feed, and that my posts may no longer show there.

You may also suggest to use custom css to hide it, which is also a fine solution as well. Thanks for building the tool!

**Comment by HermanMartinus** [comment]
You can disabled it on the post page in the dashboard by deselecting the checkbox "Show in feed". That removes the toast button and prevents it from showing up in https://bearblog.dev/discover/

**Comment by reustle** [comment]
Great, thanks Herman. May I make a small suggestion to clarify this in the UI? It is not clear that removing “show in feed” will also remove this toast button. Also, a site-wide option would be fantastic. Thanks again for all of the hard work on this great project.

**Comment by fanfare** [comment]
has this option been removed? i looked but don't see any checkbox 'Show in feed" option on the URL https://bearblog.dev/dashboard/

**Comment by HermanMartinus** [comment]
@fanfare in the header of the post set **make_discoverable: false**

This will prevent it from showing on the [discovery feed](https://bearblog.dev) and remove the **Toast this post** button

**Comment by jonasnordlund** [comment]
> Great, thanks Herman. May I make a small suggestion to clarify this in the UI? It is not clear that removing “show in feed” will also remove this toast button. Also, a site-wide option would be fantastic. Thanks again for all of the hard work on this great project.

If you want to hide the button for your site (and not be able to enable it), you can use custom CSS like this on a new, final row in a customized theme:

#upvote-form { display: none !important; }

It will still show up in the discovery feed, but if you part don't care about that and part also don't care for any "social" features, that's a workaround.

**Comment by HermanMartinus** [comment]
If you hide the upvote form with CSS it will technically be in the discover feed, but the feed is ranked by upvotes, so there's no point. If you'd like to do a site-wide *make_disoverable: false* you can add it to your post template so it's automatically there on new post creation.

**Comment by runarcn** [comment]
Hi,
Might I suggest that this be clarified in the [https://docs.bearblog.dev/post/](docs)? ie. by appending "This also removes the 'Toast' counter"
