### ISSUE TITLE
Feature request: Captions on images

### ISSUE THREAD

**Issue by shavin-peiries** [HermanMartinus/bearblog#60]
If we could have captions on images like this would be great: 

![image](https://user-images.githubusercontent.com/63689399/107450691-cc686b00-6b6b-11eb-8144-61085672312b.png)

I tried turning the ALT text into a caption using CSS but you need some javascript. 

Is there a workaround?

**Comment by rkingett** [comment]
This would be good for accessibility too, just as long as we don't get rid of the alt text option! But captions can be good for screen magnifiers.

**Comment by yunruse** [comment]
I’m not sure if it’s quite what you’re looking for, but the following might be of use. With this HTML:

```html
<figure>
  <img src="URL" alt="Foobar">
  <figcaption>Lorem ipsum</figcaption>
</figure>
```

and a sprinkling of custom CSS:

```css
figcaption {
  font-size: 0.6em;
  opacity: 0.8;
}
```

You can get some decent captions, such as used here:

![Captions in action.](https://user-images.githubusercontent.com/13365217/119128485-9d487c00-ba2d-11eb-91fc-20ff4f45c4ac.jpeg)

**Comment by shavin-peiries** [comment]
Bear editor is in markdown. How did you manipulate the HTML? 

> I’m not sure if it’s quite what you’re looking for, but the following might be of use. With this HTML:
> 
> ```
> <figure>
>   <img src="URL" alt="Foobar">
>   <figcaption>Lorem ipsum</figcaption>
> </figure>
> ```
> 
> and a sprinkling of custom CSS:
> 
> ```css
> figcaption {
>   font-size: 0.6em;
>   opacity: 0.8;
> }
> ```
> 
> You can get some decent captions, such as used here:
> 
> ![Captions in action.](https://user-images.githubusercontent.com/13365217/119128485-9d487c00-ba2d-11eb-91fc-20ff4f45c4ac.jpeg)

Bear editor is in markdown how did you edit the HTML?

**Comment by yunruse** [comment]
> Bear editor is in markdown how did you edit the HTML?

Markdown is just a convenient syntax that produces HTML. While some editors disallow embedding raw HTML for safety (eg Reddit, Discord), Bear does not.

**Comment by HermanMartinus** [comment]
Cleaning up some older issues. If you'd like to add a caption I'd use @yunruse's suggestion of writing it with HTML. Moving all feature requests to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
