### ISSUE TITLE
When you click on a tag on a page, it takes you to a search page that doesn't include that page.

### ISSUE THREAD

**Issue by josephspurrier** [HermanMartinus/bearblog#63]
Expected: When you click on a tag on a page (not a post), it takes you to a search page that includes the page in the list.

Actual: When you click on a tag on a page, it takes you to a search page that doesn't include the page you were just on.

Great tool by the way!

**Comment by HermanMartinus** [comment]
Nice catch. The search executes on the blog posts not tagged as pages, yet tags are still available on pages. There are two routes here, either:
A) Remove tags and tagging from pages
B) Add pages to the tag-searchable content

I'm inclined to go with option A. What are your thoughts?

**Comment by josephspurrier** [comment]
I thought about approach A, but then you'd have to remove the tags on the create/edit form which seems like taking away valuable functionality and adding unnecessary complexity. The tags act as an efficient way to search for 'like' topics so I'd recommend approach B and probably just show which posts are actually pages when in filter view.

**Comment by HermanMartinus** [comment]
Resolved in 7f174d5f1800ba80c2986cc32f25769be2c0bca4
