### ISSUE TITLE
Mermaid flowcharts don't work.

### ISSUE THREAD

**Issue by y-arjun-y** [HermanMartinus/bearblog#64]
Using such flowcharts will just result in the markdown text being in a white-box.

![image](https://user-images.githubusercontent.com/58625220/110231058-e446cb00-7f2e-11eb-871d-43d9612ec18b.png)

**Comment by HermanMartinus** [comment]
I'll consider supporting MermaidJS. In the meantime I recommend generating the charts elsewhere and including them as images.

**Comment by y-arjun-y** [comment]
I've been trying to add support myself, but I don't have the technical prowess to do so.

[However, I have come across a pip package that could help.](https://pypi.org/project/md-mermaid/)

**Comment by HermanMartinus** [comment]
Will take a look 👍

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
