### ISSUE TITLE
You can toast your own posts at least twice

### ISSUE THREAD

**Issue by hasenj** [HermanMartinus/bearblog#66]
From the discovery page, you can toast your own posts. Then the toast button becomes disabled.

Then you can click on the post and scroll down, the toast button is enabled there! You can click it again.

**Comment by HermanMartinus** [comment]
I can't seem to recreate this issue. If the toast was submitted then it doesn't allow a second toast anywhere. If the toast button is enabled through some error the new toast will still not be submitted as the server will see it as a duplicate and reject it. You can see the code [here](https://github.com/HermanMartinus/bearblog/blob/f8df4d287ea37a44341be875ae920a75fbe730b9/blogs/views/discover.py#L22-L27), let me know if I missed anything.

**Comment by hasenj** [comment]
Hm, I'm not able to replicate it anymore.

I reported this because out of curiosity I tried it on my own post and it worked. Although I might have done it at different times and maybe my IP changed in between.

**Comment by hasenj** [comment]
I'm not sure how or why, but I was able to replicate the issue partially. The "toast" button was enabled on the list but disabled on the page, when I clicked it on the list, it incremented the number of toasts.


https://user-images.githubusercontent.com/31078/111950733-0a22c100-8b26-11eb-8937-e49bf45cb760.mp4

**Comment by HermanMartinus** [comment]
As far as I can tell here is the flow went as follows: 
- You went to the list view, the post was untoasted
- You opened the post
- You toasted the post
- You clicked the browser "back" button which took you back to the list
- The list view showed the post had not been toasted

If I'm correct in assuming this then what happens there is the browser retains the history of the page so when you click back it doesn't do a full request. This means that the browser just shows you what was there before, which shows the post had not been toasted. 

Now while that's not ideal, the toast still won't be duplicated if you click toast again as it's checked on the server. I don't think this is much of an issue as it's how MVC works and is a pretty small corner case. 

Let me know if I'm on the right track in understanding your flow here :)

**Comment by hasenj** [comment]
Sorry I didn't clarify the video. In the video I did not toast twice - only once.

The video shows that the post was already toasted by myself, as evidence by the post page itself having the toast button disabled. None the less, I was able to toast it from the list.

**Comment by rileythomp** [comment]
I was also able to recreate this issue. 

Post is 13th with 14 toasts.

![image](https://user-images.githubusercontent.com/35535783/118856614-24b6b380-b8a5-11eb-9fc8-72ae08ab073d.png)

Still 14 toasts when I open the post.

![image](https://user-images.githubusercontent.com/35535783/118856632-2aac9480-b8a5-11eb-8e52-2c8d7f733770.png)

I toast it from the page to give it 15 toasts.

![image](https://user-images.githubusercontent.com/35535783/118856826-5b8cc980-b8a5-11eb-8aa4-84c6666619ab.png)

I go back to the discovery feed and refresh. It now has 15 toasts and is in 10th now but I'm still able to toast it.

![image](https://user-images.githubusercontent.com/35535783/118856767-4ca61700-b8a5-11eb-9f2a-262e4a3ac58c.png)

I toast it again a second time to give it 16 toasts and puts it in 7th.

![image](https://user-images.githubusercontent.com/35535783/118856801-562f7f00-b8a5-11eb-9c7a-9e223e6a27fd.png)

When I go back to the post page it says 16 toasts.

![image](https://user-images.githubusercontent.com/35535783/118856895-6f383000-b8a5-11eb-8075-88092072edc9.png)

So I was able to toast the same post twice, once from the post page and once from the discovery page, even after refreshing.

**Comment by HermanMartinus** [comment]
Under the hood the second toasts were never submitted as at the DB level there is an IP address hash which needs to be unique in oder to submit. That being said, it did show that you could post twice. 

However, this is now a non-issue as I've removed the toast button from the discovery feed in order to make sure that people who upvote have actually read the article and aren't just upvoting from the feed by title.
