### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by anakimluke** [HermanMartinus/bearblog#7]
Hi!

I saw your project on hacker news and ended up here to check out the project!

There isn't/I couldn't find any license for this repo as a whole, only what seems to be licenses for the project dependencies.

Would you consider adding some?

Thanks :)

**Comment by HermanMartinus** [comment]
Will do :) I'm a bit overwhelmed by the Hacker News Hug I got last night,
but I'll make sure to add a license. Here's the issue
https://github.com/HermanMartinus/bearblog/issues/8

Thanks!

**Comment by HermanMartinus** [comment]
MIT license added in [this commit](4007fe0ea9603cb51f986d7c99e18a7e617b9477)
