### ISSUE TITLE
Feature request: a preview button to see how the markdown will look

### ISSUE THREAD

**Issue by anthay** [HermanMartinus/bearblog#72]
I know I can save and then refresh the post in another tab, but it would be nice to either have a box that showed the post as the user will see it as you type the markdown in the edit box, or have a preview/markdown button to switch between views. It's not a high priority thing.

**Comment by rkingett** [comment]
Having a preview link, much like Wordpress, would be best for accessibility and screen reader users.

**Comment by HermanMartinus** [comment]
Completed a while back. Closing the issue 👍
