### ISSUE TITLE
Feature request: set link's preview image to the blog's emoji

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#77]
When i share a Bearblog post on Discord, the preview image is Bearblog's kaomoji bear, which is cute for sure, but isn't what my personal blog is actually about :) i can't check right now, but i guess previews elsewhere, on search engines or social networks, also show our cute bear face.
![IMG_20210507_152759](https://user-images.githubusercontent.com/80604512/117456930-08338680-af49-11eb-9ca0-615c12c344e2.png)

Would it be possible to default the preview image to the blog's selected emoji ? That would allow us to set the tone for the blog right in the preview image when it's available.

**Comment by HermanMartinus** [comment]
Makes sense. I'll add this to my list. What I'll do initially is just remove the image so it's just a text preview, then figure out if I can do something with the emoji 👍

**Comment by HermanMartinus** [comment]
Removed the Bear icon from cards in 47d622cbe1fbd5161942ff9ebb79ebd7e331f8e0 . Custom meta content will be addressed in #75
