### ISSUE TITLE
SSL Certs for Custom Domains

### ISSUE THREAD

**Issue by Whayme** [HermanMartinus/bearblog#78]
Would it be doable for custom domains to support SSL?  I would gladly pay if this were a donator-only feature, but not being able to add this to my domain without moving to cloudflare is a dealbreaker for what otherwise seems to be an absolutely ideal project.

I don't know anything about how this works, but is it possible to allow us to use certs purchased elsewhere, like through our domain registrar?  I tried to do that through Namecheap before realizing that because I don't actually have access to the server, I can't enable it.

**Comment by HermanMartinus** [comment]
It's something I'll certainly be working on in the future. It's just a bit tricky as I'm also not super confident in my ability to wrangle certificates and would ideally leave it up to Cloudflare. Let me investigate this and get back to you on this thread.

**Comment by Whayme** [comment]
[Let's Encrypt](https://letsencrypt.org/getting-started/) mentions allowing users to upload their own custom certs as a workable half-measure.  Might be easier to implement in the short term?

>If your hosting provider doesn’t want to integrate Let’s Encrypt, but does support uploading custom certificates, you can install Certbot on your own computer and use it in manual mode. In manual mode, you upload a specific file to your website to prove your control. Certbot will then retrieve a certificate that you can upload to your hosting provider. We don’t recommend this option because it is time-consuming and you will need to repeat it several times per year as your certificate expires. For most people it is better to request Let’s Encrypt support from your hosting provider, or switch providers if they do not plan to implement it.

**Comment by HermanMartinus** [comment]
Okay, so this is a doable thing. I'll have to finagle it a bit, and will update here when something is workable.

**Comment by HermanMartinus** [comment]
Okay, so I have some certificate management running. I'll be happy to set up certificates for patrons. Hopefully I'll be able to automate the entire process in the future, but right now it does take some manual work. If you'd like to have a certificate set up you can set up a [contribution](https://bearblog.dev/contribute) to the project and I'll issue a certificate for you :)
