### ISSUE TITLE
Inline CSS is HTML-escaped, breaking some features

### ISSUE THREAD

**Issue by yunruse** [HermanMartinus/bearblog#79]
Using the "Custom styling" feature will HTML-escape CSS, which mangles the CSS, as shown when viewing the DOM:

<img width="478" alt="Screenshot 2021-05-18 at 15 53 40" src="https://user-images.githubusercontent.com/13365217/118673968-58d09c80-b7f1-11eb-8246-19981c012e52.png">

This mostly affects `>` in selectors and font names.

**Comment by HermanMartinus** [comment]
Resolved in 7e53ddf42aceb83518a8edf0bb91f5ba5e4f77ce
