### ISSUE TITLE
[Feature request] The ability to specify `og:image` meta tags would be useful

### ISSUE THREAD

**Issue by yunruse** [HermanMartinus/bearblog#80]
I'm moving my blog from SquareSpace to Bear, and I have a lot of posts with their own thumbnails. While I'm not too bothered about them being shown in `/blog/`, it'd be nice to be able to set an image URL underneath the meta description which is propagated to the `og:image` and `twitter:image` meta tags.

**Comment by HermanMartinus** [comment]
Addressed in e52031130a7c92cce559f0e86b7f36ea839adc95

You can add a meta image for your home page in your [styling dashboard](https://bearblog.dev/dashboard/styles), and you can add post-specific meta images in your posts by adding the url to the image. 

Consider [contributing](https://bearblog.dev/contribute) to Bear 🙂
