### ISSUE TITLE
[Feature Request] The ability to navigate back in discovery feed

### ISSUE THREAD

**Issue by rileythomp** [HermanMartinus/bearblog#83]
After clicking 'More' on the discovery feed to get a new page, the only way to go back a page is the browser's back button. It would be nice if there was a way to navigate back a page from the site.

Also I think it would be nice to have some indication if you are on the 'Trending' or 'Newest' feed without looking at the URL, perhaps some bolding or something like that.

**Comment by HermanMartinus** [comment]
Completed in b17700b2c4549917658f3bbcaa76b4db44294a2e
