### ISSUE TITLE
Suggestion: default permalink to article's title

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#84]
From my experience, i never really write anything else in the permalink than what my title already says. Maybe sometimes a pronoun is dropped but that's it.

Can you make it so the permalink defaults to the title's text, with spaces and sepcial chars replaced by - signs instead ? it would remove an extra step to publishing for me and others as well i'm sure :)

**Comment by HermanMartinus** [comment]
I've updated it to auto-generate the permalink from the title on saving the post ddcf9f81ce3d510c0db64290ece19a35b98a5b0e 👍

Consider [contributing](https://bearblog.dev/contribute/) to Bear 🙂

**Comment by Cwpute** [comment]
> Consider [contributing](https://bearblog.dev/contribute/) to Bear 🙂

I should if i had the time and the competence to, that's why i'm using bearblog: i don't have much time nor much competence in these fields 😉 but i guess i should thank you for *your* time and competence !
