### ISSUE TITLE
[Feature request] Slightly less ambiguous titles than "Bear Blog" in the dashboard

### ISSUE THREAD

**Issue by yunruse** [HermanMartinus/bearblog#85]
This is a lil obscure I admit, but I've found myself of late going back and forth between a post I'm working on, an old post (from which I'm copy-pasting the exact syntax) and a "sandbox post". But, err, I can't disambiguate between any of the tabs, because my browser just says "Bear Blog" for them all.

Would it be possible to do something like `Post title | Bear Blog`, for editing posts and other meta pages (eg Styling)?

Many thanks once again ^^

**Comment by HermanMartinus** [comment]
Addressed in f50e006c004d17b4ea9b312bfbf4cc1ec3330178 & 407edb48eb4126b7241f0abc266da508eba39141 👍
