### ISSUE TITLE
[Feature Request] Use CSS of choice for blogger's dashboard

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#88]
I was thinking that maybe the CSS theme used for our blog's appearance could also be used for the blogger's dashboard and menus, where we write articles, browse our stats etc...
What do you think ?

**Comment by HermanMartinus** [comment]
I'll consider it and test it out 👍

**Comment by Cwpute** [comment]
I'm not sure if this is your doing but Bearblog's dashboard now seems to detect whether the browser is set to dark mode or not, and adapts itself with a dark background and white text. I realize now that this is what i was asking for mostly, when asking for "custom CSS with dashboard" as the plain white background really hurt my eyes.
![image](https://user-images.githubusercontent.com/80604512/147688645-c31e215b-edae-43c3-a129-a7db00095478.png)
I find it way better now, so thanks ? maybe ^^

I'm considering changing my suggestion to include a dark-mode/light-mode dashboard in the blog options to better reflect my issue. So, is that change of your own doing or is it something on my side ?

**Comment by HermanMartinus** [comment]
What's happening here is the default styling checks what your light/dark settings are and sets it automatically. The reason you're seeing dark mode right now is that your computer is set to dark mode. On Macs this can be set to change depending on the time of day. Currently there is still no custom styling in the dashboard. Lots of other stuff to crack at at the moment, but under consideration :)

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
