### ISSUE TITLE
Change "Publish" checkbox to a button

### ISSUE THREAD

**Issue by Cwpute** [HermanMartinus/bearblog#93]
I find having only one buton labelled "Save" to be quite misleading as to what it does, especially when you consider the "Publish" checkbox is checked by default. I find it a bit annoying, because when i write articles, i often find myself saving multiple times before actually publishing in fear i might lose my work. Yes, having to uncheck a box is a minor modification, but for me and perhaps others, it would make for a nice UX improvment :)

My suggestion would be to have two separate buttons next to each other: "Save as draft", which would save the post in the database without publishing it, and a "Publish" button which would, well... publish it :p

What do you think ?

**Comment by rkingett** [comment]
I like this suggestion! I agree. Change it to 2 buttons labeled publish, and, save as draft.

**Comment by HermanMartinus** [comment]
Makes sense to me. I'll revisit this during the course of this week 👍

**Comment by HermanMartinus** [comment]
Okay, so I've pushed an update here 5aa97e09bfc23d6b6a22e5a703aba42e6e56ad3b

Essentially it does as you suggest with a "Publish" and "Save as draft" button (when the post is not yet published). Once the post gets published, the "Save as draft" button gets changed to a "Unpublish" button as this exposes that functionality. 

Let me know if you run into any issues with this.
