### ISSUE TITLE
[Feature Request] RSS for Discovery Feed

### ISSUE THREAD

**Issue by 0066cc** [HermanMartinus/bearblog#96]
The ability to check all the latest Bear Blog posts remotely via RSS would be great for helping discover new blogs without the need to visit the Discover page manually.

The feed could follow a similar format as that used for individual Bear Blog sites so:
`https://bearblog.dev/discover/feed/`

Related:
https://github.com/HermanMartinus/bearblog/issues/2#issuecomment-636373483

**Comment by rkingett** [comment]
Agreed! This would be a great addition.

**Comment by HermanMartinus** [comment]
Thanks for the suggestion. This was a pretty neat idea. There is now an RSS feed for the trending and newest pages at https://bearblog.dev/feed/ and https://bearblog.dev/feed/?newest=True

Please let me know if you run into any issues with it.

**Comment by HermanMartinus** [comment]
Also consider [supporting Bear](https://bearblog.dev/contribute)

**Comment by Bohtega** [comment]
@HermanMartinus Hey Herman! Is this broken now? :(

**Comment by HermanMartinus** [comment]
It seems to be running for me. What issue are you experiencing? 

![Screenshot 2022-11-15 at 06 59 19](https://user-images.githubusercontent.com/26326265/201830294-13b6e09c-e79b-47fd-8c1a-fa7008baff8f.png)

**Comment by TheGithubJoshua** [comment]
Not working? ![image](https://github.com/HermanMartinus/bearblog/assets/121495559/db92e5f4-04ec-4f86-b9c0-286f41dadcec)

**Comment by TheGithubJoshua** [comment]
I didn't realize it has moved to here: https://bearblog.dev/discover/feed/
