### ISSUE TITLE
Unblock search engine indexing

### ISSUE THREAD

**Issue by a3r0net** [HermanMartinus/bearblog#97]
I would like to have my blog [a3r0.net](https://a3r0.net/) be indexed by search engines like Google and Bing, however there is a tag preventing it from being indexed.

`<meta name="robots" content="noindex" />` seems to be what's blocking it.

Any chance of a toggle to allow indexing?

**Comment by HermanMartinus** [comment]
That tag remains in place until I've reviewed the blog as we have an issue with spam blogs and I don't want search engines to blacklist the domain. Your blog has been reviewed though (I review once a day).
