### ISSUE TITLE
Ability to change the Twitter card type

### ISSUE THREAD

**Issue by ghost** [HermanMartinus/bearblog#99]
A nice yet simple feature would be if we could change the style of the Twitter card. Currently it uses the summary option, but there are others as described [here](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#display).

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
